############################################################################
# PROGRAM:  NISTEENPUF18.R                                                 #
#                                                                          #
# PURPOSE:  THIS R PROGRAM CREATES A PERMANENT R DATASET                   #
#           FROM THE 2018 NIS-TEEN PUBLIC-USE ASCII FILE                   #
#                                                                          #
# NOTES:    THIS PROGRAM IS DIVIDED INTO SEVEN STEPS AS FOLLOWS:           #
#                                                                          #
# STEP 1:   LOAD AN R PACKAGE AND ASSIGN FILE NAMES                        #
#                                                                          #
#		 ONE R PACKAGE FOR TWO FUNCTIONS (CONTENTS, WTD.TABLE)                 #
#		 WILL BE LOADED	                                                       #
#		 THE USER CAN ENTER THE PATH TO THE ASCII DATA FILE AND                #
#		 THE PATH WHERE THE R DATASET WILL BE CREATED                          #
#                                                                          #
# STEP 2:   CREATE FORMATS                                                 #
#                                                                          #
# STEP 3:   READ THE FLAT DATA FILE                                        #
#                                                                          #
# STEP 4:   ASSIGN VARIABLE LABELS                                         #
#                                                                          #
# STEP 5:   CREATE A PERMANENT R DATASET                                   #
#                                                                          #
# STEP 6:   ASSIGN FORMATS                                                 #
#                                                                          #
#	   FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES IN R	           #
#                                                                          #
# STEP 7:   CONTENTS AND STATISTICAL ESTIMATES (FREQUENCY) EXAMPLE         #
#                                                                          #
############################################################################

############################################################################
# Step 1:   LOAD R PACKAGES AND ASSIGN FILE NAMES                          #
############################################################################
#Users may need to install the Hmisc library before invoking it.
# installed and loaded in prep script
# library(Hmisc) #TO USE contents()

#---USE SLASH(/) TO SEPERATE A FILE PATH---#
# PUF <- "path-to-data"
PUF <- paste0(data_folder, "raw_data/cdc_nis_teen")

# flatfile <- "path-to-file/NISTEENPUF18.DAT"
flatfile <- paste0(PUF,"/NISTEENPUF18.DAT")


############################################################################
# Step 2:   CREATE FORMATS                                                 #
############################################################################

LANGUAGElevels=c(1,2,3)
LANGUAGElabels=c("ENGLISH", "SPANISH", "OTHER")

YNDKRFlevels=c(1,2,77,98,99)
YNDKRFlabels=c("YES", "NO", "DON'T KNOW", "MISSING IN ERROR", "REFUSED")

CKUPLASTlevels=c(1,2,3,77,98,99)
CKUPLASTlabels=c("MORE THAN (AGE - 12) YEARS AGO", "EXACTLY (AGE - 12) YEARS AGO", "LESS THAN (AGE - 12) YEARS AGO", "DON'T KNOW", "MISSING IN ERROR", "REFUSED")

CPOX_Rlevels=c(1,2,3,4,77,98,99)
CPOX_Rlabels=c("LESS THAN 1 YEAR OLD", "1 TO 5 YEARS OLD", "5 TO 10 YEARS OLD", "MORE THAN 10 YEARS OLD", "DON'T KNOW", "MISSING IN ERROR", "REFUSED")

LIKELYlevels=c(1,2,3,4,77,98,99)
LIKELYlabels=c("VERY LIKELY", "SOMEWHAT LIKELY", "NOT TOO LIKELY", "NOT LIKELY AT ALL", "NOT SURE/DON'T KNOW", "MISSING IN ERROR", "REFUSED")

INCPOVlevels=c(1,2,3,4)
INCPOVlabels=c("ABOVE POVERTY > $75K", "ABOVE POVERTY <= $75K", "BELOW POVERTY", "UNKNOWN")

MOBILlevels=c(1,2,77,98,99)
MOBILlabels=c("MOVED FROM DIFFERENT STATE", "DID NOT MOVE FROM DIFFERENT STATE", "DON'T KNOW", "MISSING IN ERROR", "REFUSED")

NUM_PHONlevels=c(1,2,3,4,77,98,99)
NUM_PHONlabels=c("ONE", "TWO", "THREE OR MORE", "NONE", "DON'T KNOW", "MISSING IN ERROR", "REFUSED")

SEXlevels=c(1,2,77,98,99)
SEXlabels=c("MALE", "FEMALE", "DON'T KNOW", "MISSING IN ERROR", "REFUSED")

ADEQlevels=c(1,2)
ADEQlabels=c("TEEN HAS ADEQUATE PROVIDER DATA", "TEEN DOES NOT HAVE ADEQUATE PROVIDER DATA")

CONSENTlevels=c(1,2)
CONSENTlabels=c("CONSENT GIVEN", "CONSENT DENIED")

IHQYNDKlevels=c(1,2,3)
IHQYNDKlabels=c("YES", "NO", "DON'T KNOW")

TYPElevels=c("","01","02","03","04","11","13","14","15","1L","1M","1N","20","21","22","30","31","32","33","43","44","4V","61","62","63","64","70","71","72","80","81","82","9V","BB","BC","BT","BU","CV","DC","DH","DK","FL","FM","FN","FO","FV","FZ","GD","HA",
"HB","HI","HO","HP","MA","MB","MM","MP","MU","NC","OT","RB","RO","TY","UN","UV","VA","VM","VO","YF")
TYPElabels=c("MISSING", "DT", "DTP", "DT/DTP/DTAP-CONTAINING, UNKNOWN SUBTYPE", "DTAP", "TD", "DT/TD-CONTAINING, UNKNOWN SUBTYPE", "TDAP", "TD/TDAP-CONTAINING, UNKNOWN SUBTYPE", "H1N1 FLU-UNKNOWN", "H1N1 FLU SPRAY", "H1N1 FLU INJECTED", "OPV", "IPV",
"POLIO-CONTAINING, UNKNOWN SUBTYPE", "MMR-ONLY", "MEASLES-ONLY", "MEASLES-MUMPS", "MEASLES-RUBELLA", "HEPB-HIB", "HIB-ONLY", "GARDASIL 4", "0.5 ML RECOMBIVAX", "1.0 ML RECOMBIVAX", "ENGERIX", "HEPATITIS B-ONLY, UNKNOWN SUBTYPE CHECKED",
"PNEUMOCOCCAL CONJUGATE", "PNEUMOCOCCAL POLYSACCHARIDE", "PNEUMOCOCCAL-CONTAINING, UKNOWN SUBTYPE", "MCV4 (MENACTRA)", "MPSV4 (MENOMUNE)", "MENINGOCOCCAL SEROGROUP ACWY, UNKNOWN SUBTYPE", "GARDASIL 9", "MENB-4C (BEXSERO)", "BCG (TUBERCULOSIS)",
"MENB-FHBP (TRUMENBA)", "MENINGOCOCCAL SEROGROUP B, UNKNOWN SUBTYPE", "CERVARIX", "DTP/DTAP COMBO", "DTP-HEPB", "DON'T KNOW", "SEASONAL FLU-CONTAINING, UNKNOWN SUBTYPE", "SEASONAL FLUMIST", "INJECTED SEASONAL FLU, OTHER/UNKNOWN SUBTYPE", "FOUR-IN-ONE",
"SEASONAL FLUVIRIN", "SEASONAL FLUZONE", "GARDASIL", "HEPATITIS A-CONTAINING, UNKNOWN SUBTYPE", "HEPATITIS B-CONTAINING, UNKNOWN SUBTYPE", "HIB-CONTAINING, UNKNOWN SUBTYPE", "HEPATITIS A-ONLY (HAVRIX OR VAQTA)", "HUMAN PAPILLOMAVIRUS, UNKNOWN SUBTYPE",
"MALARIA", "MUMPS-RUBELLA", "MEASLES-CONTAINING, UNKNOWN SUBTYPE", "MUMPS-ONLY", "MENINGOCOCCAL, UNKNOWN SEROGROUP", "NEVER CODABLE DESCRIPTION", "VERBATIM", "RUBELLA-ONLY", "ROTAVIRUS", "TYPHOID", "UNCODABLE DESCRIPTION", "GARDASIL, UNKNOWN VALENCY",
"VARICELLA-CONTAINING, UNKNOWN SUBTYPE", "MMR-VARICELLA", "VARICELLA-ONLY", "YELLOW FEVER")

UTDlevels=c(0,1)
UTDlabels=c("NOT UTD", "UTD")

CENREGlevels=c(1,2,3,4)
CENREGlabels=c("NORTHEAST", "MIDWEST", "SOUTH", "WEST")

STATElevels=c(1,10,11,12,13,15,16,17,18,19,2,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,4,40,41,42,44,45,46,47,48,49,5,50,51,53,54,55,56,6,66,72,78,8,9)
STATElabels=c("ALABAMA", "DELAWARE", "DISTRICT OF COLUMBIA", "FLORIDA", "GEORGIA", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA", "IOWA", "ALASKA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI",
"MISSOURI", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA", "OHIO", "ARIZONA", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "RHODE ISLAND", "SOUTH CAROLINA", "SOUTH DAKOTA", "TENNESSEE",
"TEXAS", "UTAH", "ARKANSAS", "VERMONT", "VIRGINIA", "WASHINGTON", "WEST VIRGINIA", "WISCONSIN", "WYOMING", "CALIFORNIA", "GUAM", "PUERTO RICO", "U.S. VIRGIN ISLANDS", "COLORADO", "CONNECTICUT")

EDUC4_Mlevels=c(1,2,3,4,77,98,99)
EDUC4_Mlabels=c("LESS THAN 12 YEARS", "12 YEARS", "MORE THAN 12 YEARS, NON-COLLEGE GRAD", "COLLEGE GRADUATE", "DON'T KNOW", "MISSING IN ERROR", "REFUSED")

FACILSUMlevels=c(1,2,3,4,5,6)
FACILSUMlabels=c("ALL PUBLIC FACILITIES", "ALL HOSPITAL FACILITIES", "ALL PRIVATE FACILITIES", "ALL STD/SCHOOL/TEEN CLINICS OR OTHER FACILITIES", "MIXED", "UNKNOWN")

REGISTRYlevels=c(1,2,3,4)
REGISTRYlabels=c("ALL PROVIDERS", "SOME BUT POSSIBLY OR DEFINITELY NOT ALL PROVIDERS", "NO PROVIDERS", "UNKNOWN/DON'T KNOW")

AGEGRP_Mlevels=c(1,2,3,77,98,99)
AGEGRP_Mlabels=c("<= 34 YEARS", "35 TO 44 YEARS", ">= 45 YEARS", "DON'T KNOW", "MISSING IN ERROR", "REFUSED")

HVSTSlevels=c(1,2,3,4,5,6,7,77,8,9,98,99)
HVSTSlabels=c("NONE", "1", "2 - 3", "4 - 5", "6 - 7", "8 - 9", "10 - 12", "DON'T KNOW", "13 - 15", "16+", "MISSING IN ERROR", "REFUSED")

RENTOWNlevels=c(1,2,3,77,99)
RENTOWNlabels=c("OWNED OR BEING BOUGHT", "RENTED", "OTHER ARRANGMENT", "DON'T KNOW", "REFUSED")

CHILDNMFlevels=c(1,2,3,77,99)
CHILDNMFlabels=c("ONE", "TWO OR THREE", "FOUR OR MORE", "DON'T KNOW", "REFUSED")

NOSCHRlevels=c(0,1,2,3,4,5,6,7,77,8,9,96,98,99)
NOSCHRlabels=c("ZERO", "ONE", "TWO", "THREE", "FOUR", "FIVE", "6 TO 9", "10 TO 19", "DON'T KNOW", "20 TO 29", "30 OR MORE", "DID NOT GO TO SCHOOL", "MISSING IN ERROR", "REFUSED")

EDUC_TRlevels=c(1,2,3,4,77,99)
EDUC_TRlabels=c("6TH TO 8TH GRADE", "9TH TO 12TH GRADE", "HS GRAD/GED COMPLETED/ENROLLED IN GED PROGRAM", "NOT IN SCHOOL/OTHER", "DON'T KNOW", "REFUSED")

C1Rlevels=c(1,2,3,4,5,6,7,8)
C1Rlabels=c("1", "2", "3", "4", "5", "6", "7", "8+")

RACE_PUFlevels=c(1,2,3)
RACE_PUFlabels=c("WHITE ONLY", "BLACK ONLY", "OTHER + MULTIPLE RACE")

RACEETHKlevels=c(1,2,3,4)
RACEETHKlabels=c("HISPANIC", "NON-HISPANIC WHITE ONLY", "NON-HISPANIC BLACK ONLY", "NON-HISPANIC OTHER + MULTIPLE RACE")

C5Rlevels=c(1,2,3,4,77,99)
C5Rlabels=c("MOTHER (STEP, FOSTER, ADOPTIVE) OR FEMALE GUARDIAN", "FATHER (STEP, FOSTER, ADOPTIVE) OR MALE GUARDIAN", "GRANDPARENT", "OTHER FAMILY MEMBER/FRIEND", "DON'T KNOW", "REFUSED")

INCQ298Alevels=c(10,11,12,13,14,3,4,5,6,7,77,8,9,99)
INCQ298Alabels=c("$35001 - $40000", "$40001 - $50000", "$50001 - $60000", "$60001 - $75000", "$75001+", "$0 - $7500", "$7501 - $10000", "$10001 - $17500", "$17501 - $20000", "$20001 - $25000", "DON'T KNOW", "$25001 - $30000", "$30001 - $35000", "REFUSED")

D6Rlevels=c(0,1,2,3)
D6Rlabels=c("0", "1", "2", "3+")

MAR_PUF2_levels=c(1,2)
MAR_PUF2_labels=c("MARRIED", "NEVER MARRIED/WIDOWED/DIVORCED/SEPARATED/DECEASED/LIVING WITH PARTNER")

ESTGRANTFlevels=c(1,10,11,12,13,14,16,17,18,19,2,20,22,25,27,28,29,30,31,34,35,36,38,4,40,41,44,46,47,49,5,50,51,54,55,56,57,58,59,6,60,61,62,63,64,65,66,68,7,72,73,74,75,76,77,8)
ESTGRANTFlabels=c("CT", "NY-REST OF STATE", "NY-CITY OF NEW YORK", "DC", "DE", "MD", "PA-REST OF STATE", "PA-PHILADELPHIA COUNTY", "VA", "WV", "MA", "AL", "FL", "GA", "KY", "MS", "NC", "SC", "TN", "IL-REST OF STATE", "IL-CITY OF CHICAGO", "IN", "MI", "ME",
"MN", "OH", "WI", "AR", "LA", "NM", "NH", "OK", "TX-REST OF STATE", "TX-CITY OF HOUSTON", "TX-BEXAR COUNTY", "IA", "KS", "MO", "NE", "RI", "CO", "MT", "ND", "SD", "UT", "WY", "AZ", "CA", "VT", "HI", "NV", "AK", "ID", "OR", "WA", "NJ")

INS_BREAK_Ilevels=c(1,2,3,4)
INS_BREAK_Ilabels=c("CURRENTLY INSURED BUT UNINSURED AT SOME POINT SINCE AGE 11", "CURRENTLY INSURED AND NEVER UNINSURED SINCE AGE 11", "CURRENTLY UNINSURED BUT INSURED AT SOME POINT SINCE AGE 11",
"CURRENTLY UNINSURED AND NEVER INSURED SINCE AGE 11")

INS_STAT2_Ilevels=c(1,2,3,4)
INS_STAT2_Ilabels=c("PRIVATE INSURANCE ONLY", "ANY MEDICAID", "OTHER INSURANCE (CHIP, IHS, MILITARY, OR OTHER, ALONE OR IN COMB. WITH PRIVATE INSURANCE)", "UNINSURED")

ESTIAPT18Flevels=c(1,10,105,107,109,11,12,13,14,16,17,18,19,2,20,22,25,27,28,29,30,31,34,35,36,38,4,40,41,44,46,47,49,5,50,51,54,55,56,57,58,59,6,60,61,62,63,64,65,66,68,7,72,73,74,75,76,77,8)
ESTIAPT18Flabels=c("CT", "NY-REST OF STATE", "GUAM", "TX-HIDALGO COUNTY", "TX-TARRANT COUNTY", "NY-CITY OF NEW YORK", "DC", "DE", "MD", "PA-REST OF STATE", "PA-PHILADELPHIA COUNTY", "VA", "WV", "MA", "AL", "FL", "GA", "KY", "MS", "NC", "SC", "TN",
"IL-REST OF STATE", "IL-CITY OF CHICAGO", "IN", "MI", "ME", "MN", "OH", "WI", "AR", "LA", "NM", "NH", "OK", "TX-REST OF STATE", "TX-CITY OF HOUSTON", "TX-BEXAR COUNTY", "IA", "KS", "MO", "NE", "RI", "CO", "MT", "ND", "SD", "UT", "WY", "AZ", "CA", "VT",
"HI", "NV", "AK", "ID", "OR", "WA", "NJ")


############################################################################
# Step 3:   READ THE FLAT DATA FILE                                        #
############################################################################

LIST.NAMEWIDTH <-
c("SEQNUMT",5,
"PDAT2",1,
"RDDWT_C",20,
"PROVWT_C",20,
"STRATUM",4,
"YEAR",4,
"ASTHMA",2,
"CKUP_11_12",2,
"CKUP_AGE",2,
"CKUP_LAST",2,
"CPOX_AGE",2,
"CPOX_AGER",2,
"CPOX_HAD",2,
"HPVI_ANY",2,
"HPVI_INTENTR",2,
"HPVI_NUM_TOT",2,
"HPVI_REAS_1",2,
"HPVI_REAS_10",2,
"HPVI_REAS_11",2,
"HPVI_REAS_12",2,
"HPVI_REAS_13",2,
"HPVI_REAS_14",2,
"HPVI_REAS_15",2,
"HPVI_REAS_16",2,
"HPVI_REAS_17",2,
"HPVI_REAS_18",2,
"HPVI_REAS_19",2,
"HPVI_REAS_2",2,
"HPVI_REAS_20",2,
"HPVI_REAS_21",2,
"HPVI_REAS_22",2,
"HPVI_REAS_23",2,
"HPVI_REAS_24",2,
"HPVI_REAS_25",2,
"HPVI_REAS_26",2,
"HPVI_REAS_27",2,
"HPVI_REAS_28",2,
"HPVI_REAS_29",2,
"HPVI_REAS_3",2,
"HPVI_REAS_30",2,
"HPVI_REAS_31",2,
"HPVI_REAS_5",2,
"HPVI_REAS_6",2,
"HPVI_REAS_9",2,
"HPVI_RECOM",2,
"IMM_ANY",2,
"MEN_ANY",2,
"MEN_NUM_TOT",2,
"MEN_REAS_1",2,
"MEN_REAS_10",2,
"MEN_REAS_11",2,
"MEN_REAS_12",2,
"MEN_REAS_13",2,
"MEN_REAS_14",2,
"MEN_REAS_15",2,
"MEN_REAS_16",2,
"MEN_REAS_17",2,
"MEN_REAS_18",2,
"MEN_REAS_19",2,
"MEN_REAS_2",2,
"MEN_REAS_20",2,
"MEN_REAS_21",2,
"MEN_REAS_22",2,
"MEN_REAS_23",2,
"MEN_REAS_24",2,
"MEN_REAS_25",2,
"MEN_REAS_3",2,
"MEN_REAS_4",2,
"MEN_REAS_5",2,
"MEN_REAS_6",2,
"MEN_REAS_7",2,
"NOSCHOOLR",2,
"RISK_EVER",2,
"RISK_HH",2,
"RISK_NOW",2,
"TET_ANY",2,
"TET_REAS_1",2,
"TET_REAS_10",2,
"TET_REAS_11",2,
"TET_REAS_12",2,
"TET_REAS_13",2,
"TET_REAS_14",2,
"TET_REAS_15",2,
"TET_REAS_16",2,
"TET_REAS_17",2,
"TET_REAS_18",2,
"TET_REAS_19",2,
"TET_REAS_2",2,
"TET_REAS_20",2,
"TET_REAS_21",2,
"TET_REAS_22",2,
"TET_REAS_23",2,
"TET_REAS_24",2,
"TET_REAS_25",2,
"TET_REAS_26",2,
"TET_REAS_3",2,
"TET_REAS_4",2,
"TET_REAS_5",2,
"TET_REAS_7",2,
"VISITS",2,
"AGE",2,
"AGEGRP_M_I",1,
"C1R",1,
"C5R",2,
"CEN_REG",1,
"CHILDNM",1,
"EDUC1",1,
"EDUC_TR",2,
"INCPORAR",16,
"INCPORAR_I",16,
"INCPOV1",1,
"INCQ298A",2,
"I_HISP_K",1,
"LANGUAGE",1,
"MARITAL2",1,
"MOBIL_I",1,
"NUM_PHONE",2,
"NUM_CELLS_HH",2,
"NUM_CELLS_PARENTS",2,
"RACEETHK",1,
"RACE_K",1,
"RENT_OWN",2,
"SEX",1,
"ESTIAPT18",3,
"EST_GRANT",2,
"STATE",2,
"D6R",1,
"D7",1,
"NUM_PROVR",1,
"N_PRVR",1,
"FACILITY",1,
"REGISTRY",1,
"VFC_ORDER",1,
"WELLCHILD",1,
"P_N13HPV",1,
"P_N13HPV_4V",1,
"P_N13HPV_9V",1,
"P_N13HPV_CV",1,
"P_N13HPV_HP",1,
"P_N13HPV_UV",1,
"P_N13MEN",1,
"P_N13MEN_80",1,
"P_N13MEN_81",1,
"P_N13MEN_82",1,
"P_N13MENB",1,
"P_N13MENB_BB",1,
"P_N13MENB_BT",1,
"P_N13MENB_BU",1,
"P_N13MENU",1,
"P_N13TDAP_POST10",1,
"P_N13TDAP_POST7",1,
"P_N13TDP",1,
"P_N13TDP_11",1,
"P_N13TDP_14",1,
"P_N13TDP_15",1,
"P_N13TDP_POST10",1,
"P_NUMHPV",1,
"P_NUMHPV_4V",1,
"P_NUMHPV_9V",1,
"P_NUMHPV_CV",1,
"P_NUMHPV_HP",1,
"P_NUMHPV_UV",1,
"P_NUMMEN",1,
"P_NUMMEN_80",1,
"P_NUMMEN_81",1,
"P_NUMMEN_82",1,
"P_NUMMENB",1,
"P_NUMMENB_BB",1,
"P_NUMMENB_BT",1,
"P_NUMMENB_BU",1,
"P_NUMMENU",1,
"P_NUMTDAP_POST10",1,
"P_NUMTDAP_POST7",1,
"P_NUMTDP",1,
"P_NUMTDP_11",1,
"P_NUMTDP_14",1,
"P_NUMTDP_15",1,
"P_NUMTDP_POST10",1,
"P_U13HPV",1,
"P_U13HPV3",1,
"P_U13113",1,
"P_U13MEN",1,
"P_U13TD",1,
"P_U13TDAP",1,
"P_U13TDAP7",1,
"P_UTDHPV",1,
"P_UTDHPV_15",1,
"P_UTDHPV_15INT",1,
"P_UTDHPV_9V",1,
"P_UTDHPV11",1,
"P_UTDHPV12",1,
"P_UTDHPV13",1,
"P_UTDHPV2",1,
"P_UTDHPV2_9V",1,
"P_UTDHPV3",1,
"P_UTDHPV3_9V",1,
"P_UTDHPV3C",1,
"P_UTDHPV3C_15INT",1,
"P_UTDHPV3C_9V",1,
"P_UTDMEN",1,
"P_UTDMENACWY",1,
"P_UTDTD",1,
"P_UTDTDAP",1,
"P_UTDTDAP7",1,
"P_UTDTDP_POST10",1,
"P_UTDTD_POST10",1,
"HPV_AGE1",2,
"HPV_AGE2",2,
"HPV_AGE3",2,
"HPV_AGE4",2,
"HPV_AGE5",2,
"HPV_AGE6",2,
"HPV_AGE7",1,
"HPV_AGE8",1,
"HPV_AGE9",1,
"HPV_DAGE1",4,
"HPV_DAGE2",4,
"HPV_DAGE3",4,
"HPV_DAGE4",4,
"HPV_DAGE5",4,
"HPV_DAGE6",4,
"HPV_DAGE7",1,
"HPV_DAGE8",1,
"HPV_DAGE9",1,
"HPV_MAGE1",3,
"HPV_MAGE2",3,
"HPV_MAGE3",3,
"HPV_MAGE4",3,
"HPV_MAGE5",3,
"HPV_MAGE6",3,
"HPV_MAGE7",1,
"HPV_MAGE8",1,
"HPV_MAGE9",1,
"MEN_AGE1",2,
"MEN_AGE2",2,
"MEN_AGE3",2,
"MEN_AGE4",2,
"MEN_AGE5",1,
"MEN_AGE6",1,
"MEN_AGE7",1,
"MEN_AGE8",1,
"MEN_AGE9",1,
"MEN_DAGE1",4,
"MEN_DAGE2",4,
"MEN_DAGE3",4,
"MEN_DAGE4",4,
"MEN_DAGE5",1,
"MEN_DAGE6",1,
"MEN_DAGE7",1,
"MEN_DAGE8",1,
"MEN_DAGE9",1,
"MEN_MAGE1",3,
"MEN_MAGE2",3,
"MEN_MAGE3",3,
"MEN_MAGE4",3,
"MEN_MAGE5",1,
"MEN_MAGE6",1,
"MEN_MAGE7",1,
"MEN_MAGE8",1,
"MEN_MAGE9",1,
"MENB_AGE1",2,
"MENB_AGE2",2,
"MENB_AGE3",2,
"MENB_AGE4",1,
"MENB_AGE5",1,
"MENB_AGE6",1,
"MENB_AGE7",1,
"MENB_AGE8",1,
"MENB_AGE9",1,
"MENB_DAGE1",4,
"MENB_DAGE2",4,
"MENB_DAGE3",4,
"MENB_DAGE4",1,
"MENB_DAGE5",1,
"MENB_DAGE6",1,
"MENB_DAGE7",1,
"MENB_DAGE8",1,
"MENB_DAGE9",1,
"MENB_MAGE1",3,
"MENB_MAGE2",3,
"MENB_MAGE3",3,
"MENB_MAGE4",1,
"MENB_MAGE5",1,
"MENB_MAGE6",1,
"MENB_MAGE7",1,
"MENB_MAGE8",1,
"MENB_MAGE9",1,
"MENU_AGE1",2,
"MENU_AGE2",2,
"MENU_AGE3",1,
"MENU_AGE4",1,
"MENU_AGE5",1,
"MENU_AGE6",1,
"MENU_AGE7",1,
"MENU_AGE8",1,
"MENU_AGE9",1,
"MENU_DAGE1",4,
"MENU_DAGE2",4,
"MENU_DAGE3",1,
"MENU_DAGE4",1,
"MENU_DAGE5",1,
"MENU_DAGE6",1,
"MENU_DAGE7",1,
"MENU_DAGE8",1,
"MENU_DAGE9",1,
"MENU_MAGE1",3,
"MENU_MAGE2",3,
"MENU_MAGE3",1,
"MENU_MAGE4",1,
"MENU_MAGE5",1,
"MENU_MAGE6",1,
"MENU_MAGE7",1,
"MENU_MAGE8",1,
"MENU_MAGE9",1,
"TDP_AGE1",2,
"TDP_AGE2",2,
"TDP_AGE3",2,
"TDP_AGE4",2,
"TDP_AGE5",1,
"TDP_AGE6",1,
"TDP_AGE7",1,
"TDP_AGE8",1,
"TDP_AGE9",1,
"TDP_DAGE1",4,
"TDP_DAGE2",4,
"TDP_DAGE3",4,
"TDP_DAGE4",4,
"TDP_DAGE5",1,
"TDP_DAGE6",1,
"TDP_DAGE7",1,
"TDP_DAGE8",1,
"TDP_DAGE9",1,
"TDP_MAGE1",3,
"TDP_MAGE2",3,
"TDP_MAGE3",3,
"TDP_MAGE4",3,
"TDP_MAGE5",1,
"TDP_MAGE6",1,
"TDP_MAGE7",1,
"TDP_MAGE8",1,
"TDP_MAGE9",1,
"XHPVTY1",2,
"XHPVTY2",2,
"XHPVTY3",2,
"XHPVTY4",2,
"XHPVTY5",2,
"XHPVTY6",2,
"XHPVTY7",1,
"XHPVTY8",1,
"XHPVTY9",1,
"XMENBTY1",2,
"XMENBTY2",2,
"XMENBTY3",2,
"XMENBTY4",1,
"XMENBTY5",1,
"XMENBTY6",1,
"XMENBTY7",1,
"XMENBTY8",1,
"XMENBTY9",1,
"XMENTY1",2,
"XMENTY2",2,
"XMENTY3",2,
"XMENTY4",2,
"XMENTY5",1,
"XMENTY6",1,
"XMENTY7",1,
"XMENTY8",1,
"XMENTY9",1,
"XTDPTY1",2,
"XTDPTY2",2,
"XTDPTY3",2,
"XTDPTY4",2,
"XTDPTY5",1,
"XTDPTY6",1,
"XTDPTY7",1,
"XTDPTY8",1,
"XTDPTY9",1,
"INS_STAT2_I",1,
"INS_BREAK_I",1
)

NAMEWIDTH <- matrix(LIST.NAMEWIDTH, 379, 2, byrow=T, dimnames = list(NULL, c("VARIABLE","WIDTH")))
NA_STRING <- c(" ", ".", " .", "  .", "   .", "   .    ", " .              ", "    .              ", "     .              ", "     .             ")

NISTEENPUF18 <- read.fwf(flatfile, widths= as.numeric(NAMEWIDTH[,2]), col.names = NAMEWIDTH[,1], na.strings= NA_STRING, as.is=TRUE)

NISTEENPUF18$SEQNUMT <- as.character(NISTEENPUF18$SEQNUMT)
NISTEENPUF18$XHPVTY1 <- as.character(NISTEENPUF18$XHPVTY1)
NISTEENPUF18$XHPVTY2 <- as.character(NISTEENPUF18$XHPVTY2)
NISTEENPUF18$XHPVTY3 <- as.character(NISTEENPUF18$XHPVTY3)
NISTEENPUF18$XHPVTY4 <- as.character(NISTEENPUF18$XHPVTY4)
NISTEENPUF18$XHPVTY5 <- as.character(NISTEENPUF18$XHPVTY5)
NISTEENPUF18$XHPVTY6 <- as.character(NISTEENPUF18$XHPVTY6)
NISTEENPUF18$XHPVTY7 <- as.character(NISTEENPUF18$XHPVTY7)
NISTEENPUF18$XHPVTY8 <- as.character(NISTEENPUF18$XHPVTY8)
NISTEENPUF18$XHPVTY9 <- as.character(NISTEENPUF18$XHPVTY9)
NISTEENPUF18$XMENBTY1 <- as.character(NISTEENPUF18$XMENBTY1)
NISTEENPUF18$XMENBTY2 <- as.character(NISTEENPUF18$XMENBTY2)
NISTEENPUF18$XMENBTY3 <- as.character(NISTEENPUF18$XMENBTY3)
NISTEENPUF18$XMENBTY4 <- as.character(NISTEENPUF18$XMENBTY4)
NISTEENPUF18$XMENBTY5 <- as.character(NISTEENPUF18$XMENBTY5)
NISTEENPUF18$XMENBTY6 <- as.character(NISTEENPUF18$XMENBTY6)
NISTEENPUF18$XMENBTY7 <- as.character(NISTEENPUF18$XMENBTY7)
NISTEENPUF18$XMENBTY8 <- as.character(NISTEENPUF18$XMENBTY8)
NISTEENPUF18$XMENBTY9 <- as.character(NISTEENPUF18$XMENBTY9)
NISTEENPUF18$XMENTY1 <- as.character(NISTEENPUF18$XMENTY1)
NISTEENPUF18$XMENTY2 <- as.character(NISTEENPUF18$XMENTY2)
NISTEENPUF18$XMENTY3 <- as.character(NISTEENPUF18$XMENTY3)
NISTEENPUF18$XMENTY4 <- as.character(NISTEENPUF18$XMENTY4)
NISTEENPUF18$XMENTY5 <- as.character(NISTEENPUF18$XMENTY5)
NISTEENPUF18$XMENTY6 <- as.character(NISTEENPUF18$XMENTY6)
NISTEENPUF18$XMENTY7 <- as.character(NISTEENPUF18$XMENTY7)
NISTEENPUF18$XMENTY8 <- as.character(NISTEENPUF18$XMENTY8)
NISTEENPUF18$XMENTY9 <- as.character(NISTEENPUF18$XMENTY9)
NISTEENPUF18$XTDPTY1 <- as.character(NISTEENPUF18$XTDPTY1)
NISTEENPUF18$XTDPTY2 <- as.character(NISTEENPUF18$XTDPTY2)
NISTEENPUF18$XTDPTY3 <- as.character(NISTEENPUF18$XTDPTY3)
NISTEENPUF18$XTDPTY4 <- as.character(NISTEENPUF18$XTDPTY4)
NISTEENPUF18$XTDPTY5 <- as.character(NISTEENPUF18$XTDPTY5)
NISTEENPUF18$XTDPTY6 <- as.character(NISTEENPUF18$XTDPTY6)
NISTEENPUF18$XTDPTY7 <- as.character(NISTEENPUF18$XTDPTY7)
NISTEENPUF18$XTDPTY8 <- as.character(NISTEENPUF18$XTDPTY8)
NISTEENPUF18$XTDPTY9 <- as.character(NISTEENPUF18$XTDPTY9)

############################################################################
# Step 4:   ASSIGN VARIABLE LABELS                                         #
############################################################################

label(NISTEENPUF18$SEQNUMT) <- "UNIQUE TEEN IDENTIFIER"
label(NISTEENPUF18$PDAT2) <- "ADEQUATE PROVIDER DATA FLAG"
label(NISTEENPUF18$RDDWT_C) <- "FINAL SINGLE-FRAME CELL-PHONE RDD-PHASE WEIGHT (EXCLUDES TERRITORIES)"
label(NISTEENPUF18$PROVWT_C) <- "FINAL SINGLE-FRAME CELL-PHONE PROVIDER-PHASE WEIGHT (EXCLUDES TERRITORIES)"
label(NISTEENPUF18$STRATUM) <- "STRATUM VARIABLE FOR VARIANCE ESTIMATION"

label(NISTEENPUF18$YEAR) <- "SAMPLING YEAR"
label(NISTEENPUF18$ASTHMA) <- "HAS TEEN BEEN TOLD BY DOCTOR OR OTHER HEALTH PROFESSIONAL THAT HE/SHE HAS ASTHMA?"
label(NISTEENPUF18$CKUP_11_12) <- "DID TEEN HAVE AN 11-12 YEAR OLD WELL-CHILD EXAM OR CHECK-UP?"
label(NISTEENPUF18$CKUP_AGE) <- "AGE IN YEARS AT LAST CHECK-UP"
label(NISTEENPUF18$CKUP_LAST) <- "WAS TEEN'S LAST CHECK-UP MORE OR LESS THAN (AGE - 12) YEARS AGO?"

label(NISTEENPUF18$CPOX_AGE) <- "AGE IN YEARS WHEN HAD CHICKEN POX DISEASE"
label(NISTEENPUF18$CPOX_AGER) <- "AGE RANGE WHEN HAD CHICKEN POX DISEASE"
label(NISTEENPUF18$CPOX_HAD) <- "TEEN EVER HAD CHICKEN POX DISEASE?"
label(NISTEENPUF18$HPVI_ANY) <- "HH-REPORT: HAS TEEN EVER RECEIVED ANY HUMAN PAPILLOMAVIRUS SHOTS?"
label(NISTEENPUF18$HPVI_INTENTR) <- "HOW LIKELY IS IT TEEN WILL RECEIVE HPV SHOTS IN NEXT 12 MONTHS?"

label(NISTEENPUF18$HPVI_NUM_TOT) <- "NUMBER OF HH-REPORTED HUMAN PAPILLOMAVIRUS SHOTS RECEIVED (TOTAL)"
label(NISTEENPUF18$HPVI_REAS_1) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: NOT RECOMMENDED"
label(NISTEENPUF18$HPVI_REAS_10) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: COSTS"
label(NISTEENPUF18$HPVI_REAS_11) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: SAFETY CONCERN/SIDE EFFECTS"
label(NISTEENPUF18$HPVI_REAS_12) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: EFFECTIVENESS CONCERN"

label(NISTEENPUF18$HPVI_REAS_13) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: CHILD FEARFUL"
label(NISTEENPUF18$HPVI_REAS_14) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: CHILD SHOULD MAKE DECISION"
label(NISTEENPUF18$HPVI_REAS_15) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: COLLEGE SHOT"
label(NISTEENPUF18$HPVI_REAS_16) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: DON'T BELIEVE IN IMMUNIZATIONS"
label(NISTEENPUF18$HPVI_REAS_17) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: FAMILY/PARENTAL DECISION"

label(NISTEENPUF18$HPVI_REAS_18) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: HANDICAPPED/SPECIAL NEEDS/ILLNESS"
label(NISTEENPUF18$HPVI_REAS_19) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: RELIGION/ORTHODOX"
label(NISTEENPUF18$HPVI_REAS_2) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: NOT NEEDED OR NOT NECESSARY"
label(NISTEENPUF18$HPVI_REAS_20) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: TIME"
label(NISTEENPUF18$HPVI_REAS_21) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: MORE INFO/NEW VACCINE"

label(NISTEENPUF18$HPVI_REAS_22) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: ALREADY UP-TO-DATE"
label(NISTEENPUF18$HPVI_REAS_23) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: NOT AVAILABLE"
label(NISTEENPUF18$HPVI_REAS_24) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: NOT A SCHOOL REQUIREMENT"
label(NISTEENPUF18$HPVI_REAS_25) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: INCREASED SEXUAL ACTIVITY CONCERN"
label(NISTEENPUF18$HPVI_REAS_26) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: NO OB/GYN"

label(NISTEENPUF18$HPVI_REAS_27) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: ALREADY SEXUALLY ACTIVE"
label(NISTEENPUF18$HPVI_REAS_28) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: NO DOCTOR OR DOCTOR'S VISIT NOT SCHEDULED"
label(NISTEENPUF18$HPVI_REAS_29) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: CHILD IS MALE"
label(NISTEENPUF18$HPVI_REAS_3) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: LACK OF KNOWLEDGE"
label(NISTEENPUF18$HPVI_REAS_30) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: INTEND TO COMPLETE BUT HAVE NOT YET/ALREADY PLANNED"

label(NISTEENPUF18$HPVI_REAS_31) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: DIFFICULTY MAKING OR GETTING TO APPOINTMENT/TRANSPORTATION PROBLEMS"
label(NISTEENPUF18$HPVI_REAS_5) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: NOT SEXUALLY ACTIVE"
label(NISTEENPUF18$HPVI_REAS_6) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: NOT APPROPRIATE AGE"
label(NISTEENPUF18$HPVI_REAS_9) <- "MAIN REASON TEEN WILL NOT RECEIVE HUMAN PAPILLOMAVIRUS SHOTS IN THE NEXT 12 MONTHS: OTHER REASON"
label(NISTEENPUF18$HPVI_RECOM) <- "HAD OR HAS DOCTOR OR OTHER HEALTH CARE PROFESSIONAL EVER RECOMMENDED THAT TEEN RECEIVE HPV SHOTS?"

label(NISTEENPUF18$IMM_ANY) <- "HH-REPORT: HAS TEEN EVER RECEIVED ANY VACCINATIONS?"
label(NISTEENPUF18$MEN_ANY) <- "HH-REPORT: HAS TEEN EVER RECEIVED ANY MENINGITIS SHOTS?"
label(NISTEENPUF18$MEN_NUM_TOT) <- "NUMBER OF HH-REPORTED MENINGITIS SHOTS RECEIVED (TOTAL)"
label(NISTEENPUF18$MEN_REAS_1) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: NOT RECOMMENDED"
label(NISTEENPUF18$MEN_REAS_10) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: COSTS"

label(NISTEENPUF18$MEN_REAS_11) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: SAFETY CONCERN/SIDE EFFECTS"
label(NISTEENPUF18$MEN_REAS_12) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: EFFECTIVENESS CONCERN"
label(NISTEENPUF18$MEN_REAS_13) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: CHILD FEARFUL"
label(NISTEENPUF18$MEN_REAS_14) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: CHILD SHOULD MAKE DECISION"
label(NISTEENPUF18$MEN_REAS_15) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: COLLEGE SHOT"

label(NISTEENPUF18$MEN_REAS_16) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: DON'T BELIEVE IN VACCINATIONS"
label(NISTEENPUF18$MEN_REAS_17) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: FAMILY/PARENTAL DECISION"
label(NISTEENPUF18$MEN_REAS_18) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: HANDICAPPED/SPECIAL NEEDS/ILLNESS"
label(NISTEENPUF18$MEN_REAS_19) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: RELIGION/ORTHODOX"
label(NISTEENPUF18$MEN_REAS_2) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: LACK OF KNOWLEDGE"

label(NISTEENPUF18$MEN_REAS_20) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: TIME"
label(NISTEENPUF18$MEN_REAS_21) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: MORE INFO/NEW VACCINE"
label(NISTEENPUF18$MEN_REAS_22) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: ALREADY UP-TO-DATE"
label(NISTEENPUF18$MEN_REAS_23) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: NO DOCTOR OR DOCTOR'S VISIT NOT SCHEDULED"
label(NISTEENPUF18$MEN_REAS_24) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: INTEND TO COMPLETE BUT HAVE NOT YET/ALREADY PLANNED"

label(NISTEENPUF18$MEN_REAS_25) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: DIFFICULTY MAKING OR GETTING TO APPOINTMENT/TRANSPORTATION PROBLEMS"
label(NISTEENPUF18$MEN_REAS_3) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: NOT NEEDED OR NOT NECESSARY"
label(NISTEENPUF18$MEN_REAS_4) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: NOT SCHOOL REQUIREMENT"
label(NISTEENPUF18$MEN_REAS_5) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: NOT AVAILABLE"
label(NISTEENPUF18$MEN_REAS_6) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: NOT APPROPRIATE AGE"

label(NISTEENPUF18$MEN_REAS_7) <- "MAIN REASON TEEN DID NOT RECEIVE MENINGITIS SHOTS: OTHER REASON"
label(NISTEENPUF18$NOSCHOOLR) <- "DURING PAST 12 MONTHS, ABOUT HOW MANY DAYS DID TEEN MISS SCHOOL BECAUSE OF ILLNESS OR INJURY? (RECODE)"
label(NISTEENPUF18$RISK_EVER) <- "HAS DOCTOR, NURSE, OR OTHER HEALTH CARE PROFESSIONAL EVER SAID THAT TEEN HAS HAD ANY OF THE FOLLOWING HEALTH CONDITIONS?"
label(NISTEENPUF18$RISK_HH) <- "DO ANY OTHER MEMBERS OF TEEN'S HOUSEHOLD HAVE ANY OF THE FOLLOWING HEALTH CONDITIONS?"
label(NISTEENPUF18$RISK_NOW) <- "DOES TEEN STILL HAVE ANY OF THESE CONDITIONS?"

label(NISTEENPUF18$TET_ANY) <- "HH-REPORT: HAS TEEN EVER RECEIVED ANY TETANUS BOOSTER SHOTS?"
label(NISTEENPUF18$TET_REAS_1) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: NOT RECOMMENDED"
label(NISTEENPUF18$TET_REAS_10) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: COSTS"
label(NISTEENPUF18$TET_REAS_11) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: SAFETY CONCERN/SIDE EFFECTS"
label(NISTEENPUF18$TET_REAS_12) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: EFFECTIVENESS CONCERN"

label(NISTEENPUF18$TET_REAS_13) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: CHILD FEARFUL"
label(NISTEENPUF18$TET_REAS_14) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: CHILD SHOULD MAKE DECISION"
label(NISTEENPUF18$TET_REAS_15) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: COLLEGE SHOT"
label(NISTEENPUF18$TET_REAS_16) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: DON'T BELIEVE IN VACCINATIONS"
label(NISTEENPUF18$TET_REAS_17) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: FAMILY/PARENTAL DECISION"

label(NISTEENPUF18$TET_REAS_18) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: HANDICAPPED/SPECIAL NEEDS/ILLNESS"
label(NISTEENPUF18$TET_REAS_19) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: RELIGION/ORTHODOX"
label(NISTEENPUF18$TET_REAS_2) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: LACK OF KNOWLEDGE"
label(NISTEENPUF18$TET_REAS_20) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: TIME"
label(NISTEENPUF18$TET_REAS_21) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: MORE INFO/NEW VACCINE"

label(NISTEENPUF18$TET_REAS_22) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: ALREADY UP-TO-DATE"
label(NISTEENPUF18$TET_REAS_23) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: NOT AVAILABLE"
label(NISTEENPUF18$TET_REAS_24) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: NOT A SCHOOL REQUIREMENT"
label(NISTEENPUF18$TET_REAS_25) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: INTEND TO COMPLETE BUT HAVE NOT YET/ALREADY PLANNED"
label(NISTEENPUF18$TET_REAS_26) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: DIFFICULTY MAKING OR GETTING TO APPOINTMENT/TRANSPORTATION PROBLEMS"

label(NISTEENPUF18$TET_REAS_3) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: NOT NEEDED OR NOT NECESSARY"
label(NISTEENPUF18$TET_REAS_4) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: NO DOCTOR OR DOCTOR'S VISIT NOT SCHEDULED"
label(NISTEENPUF18$TET_REAS_5) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: NOT APPROPRIATE AGE"
label(NISTEENPUF18$TET_REAS_7) <- "MAIN REASON TEEN DID NOT RECEIVE TETANUS BOOSTER SHOTS: OTHER REASON"
label(NISTEENPUF18$VISITS) <- "IN PAST 12 MONTHS NUMBER OF TIMES TEEN HAS SEEN A DOCTOR OR OTHER HEALTH CARE PROFESSIONAL"

label(NISTEENPUF18$AGE) <- "AGE IN YEARS OF SELECTED TEEN"
label(NISTEENPUF18$AGEGRP_M_I) <- "MOTHER'S AGE CATEGORIES: IMPUTED (RECODE)"
label(NISTEENPUF18$C1R) <- "NUMBER OF PEOPLE IN HOUSEHOLD (RECODE)"
label(NISTEENPUF18$C5R) <- "RELATIONSHIP OF RESPONDENT TO TEEN (RECODE)"
label(NISTEENPUF18$CEN_REG) <- "CENSUS REGION BASED ON TRUE STATE OF RESIDENCE"

label(NISTEENPUF18$CHILDNM) <- "NUMBER OF CHILDREN UNDER 18 YEARS OF AGE IN HH (RECODE)"
label(NISTEENPUF18$EDUC1) <- "EDUCATION LEVEL OF MOTHER WITH 4 CATEGORIES: IMPUTED (RECODE)"
label(NISTEENPUF18$EDUC_TR) <- "TEEN'S CURRENT GRADE IN SCHOOL (RECODE)"
label(NISTEENPUF18$INCPORAR) <- "INCOME TO POVERTY RATIO (RECODE)"
label(NISTEENPUF18$INCPORAR_I) <- "INCOME TO POVERTY RATIO: IMPUTED (RECODE)"

label(NISTEENPUF18$INCPOV1) <- "POVERTY STATUS"
label(NISTEENPUF18$INCQ298A) <- "FAMILY INCOME CATEGORIES (RECODE)"
label(NISTEENPUF18$I_HISP_K) <- "IS TEEN HISPANIC OR LATINO?: IMPUTED"
label(NISTEENPUF18$LANGUAGE) <- "LANGUAGE IN WHICH INTERVIEW WAS CONDUCTED"
label(NISTEENPUF18$MARITAL2) <- "MARITAL STATUS OF MOTHER: IMPUTED (RECODE)"

label(NISTEENPUF18$MOBIL_I) <- "GEOGRAPHIC MOBILITY STATUS: STATE OF RESIDENCE AT BIRTH VERSUS CURRENT STATE: IMPUTED"
label(NISTEENPUF18$NUM_PHONE) <- "NUMBER OF RESIDENTIAL TELEPHONE NUMBERS IN HOUSEHOLD (EXCLUDING CELL PHONES)"
label(NISTEENPUF18$NUM_CELLS_HH) <- "NUMBER OF WORKING CELL PHONES HOUSEHOLD MEMBERS HAVE AVAILABLE FOR PERSONAL USE"
label(NISTEENPUF18$NUM_CELLS_PARENTS) <- "NUMBER OF WORKING CELL PHONES USUALLY USED BY PARENTS OR GUARDIANS"
label(NISTEENPUF18$RACEETHK) <- "RACE/ETHNICITY OF TEEN WITH MULTIRACE CATEGORY: IMPUTED (RECODE)"

label(NISTEENPUF18$RACE_K) <- "RACE OF TEEN WITH MULTIRACE CATEGORY: IMPUTED (RECODE)"
label(NISTEENPUF18$RENT_OWN) <- "IS HOME OWNED/BEING BOUGHT, RENTED, OR OCCUPIED BY SOME OTHER ARRANGEMENT?"
label(NISTEENPUF18$SEX) <- "SEX OF TEEN: IMPUTED"
label(NISTEENPUF18$ESTIAPT18) <- "ESTIMATION AREA OF RESIDENCE"
label(NISTEENPUF18$EST_GRANT) <- "AREA OF RESIDENCE PER THE 56 CORE NIS GRANTEE AREAS"

label(NISTEENPUF18$STATE) <- "TRUE STATE OF RESIDENCE (STATE FIPS CODE)"
label(NISTEENPUF18$D6R) <- "NUMBER OF PROVIDERS IDENTIFIED BY RESPONDENT (NOT DE-DUPLICATED) (RECODE)"
label(NISTEENPUF18$D7) <- "CONSENT TO OBTAIN VACCINATION RECORDS FROM PROVIDERS"
label(NISTEENPUF18$NUM_PROVR) <- "NUMBER OF VALID, UNIQUE PROVIDERS IDENTIFIED BY RESPONDENT (FOR TEENS WITH CONSENT) (RECODE)"
label(NISTEENPUF18$N_PRVR) <- "NUMBER OF IHQS WITH VACCINATION INFORMATION FOR THE TEEN (RECODE)"

label(NISTEENPUF18$FACILITY) <- "FACILITY TYPES FOR TEEN'S PROVIDERS"
label(NISTEENPUF18$REGISTRY) <- "DID TEEN'S PROVIDERS REPORT TEEN'S IMMUNIZATIONS TO IMMUNIZATION REGISTRY?"
label(NISTEENPUF18$VFC_ORDER) <- "DO TEEN'S PROVIDERS ORDER VACCINES FROM STATE/LOCAL HEALTH DEPT?"
label(NISTEENPUF18$WELLCHILD) <- "DID TEEN RECEIVE AN 11-12 YEAR OLD WELL CHILD EXAM OR CHECK-UP?"
label(NISTEENPUF18$P_N13HPV) <- "NUMBER OF HUMAN PAPILLOMAVIRUS SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_N13HPV_4V) <- "NUMBER OF HPV-GARDASIL (4vHPV) SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13HPV_9V) <- "NUMBER OF HPV-GARDASIL 9 (9vHPV) SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13HPV_CV) <- "NUMBER OF HPV-CERVARIX SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13HPV_HP) <- "NUMBER OF HPV SHOTS OF UNKNOWN TYPE BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13HPV_UV) <- "NUMBER OF HPV-GARDASIL, UNKNOWN VALENCY SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_N13MEN) <- "NUMBER OF MENINGOCOCCAL SEROGROUP ACWY-CONTAINING SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13MEN_80) <- "NUMBER OF MENINGOCOCCAL MCV4 SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13MEN_81) <- "NUMBER OF MENINGOCOCCAL MPSV4 SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13MEN_82) <- "NUMBER OF MENINGOCOCCAL SEROGROUP ACWY SHOTS OF UNKNOWN TYPE BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13MENB) <- "NUMBER OF MENINGOCOCCAL SEROGROUP B SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_N13MENB_BB) <- "NUMBER OF MENINGOCOCCAL MENB-4C SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13MENB_BT) <- "NUMBER OF MENINGOCOCCAL MENB-FHPB SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13MENB_BU) <- "NUMBER OF MENINGOCOCCAL SEROGROUP B SHOTS OF UNKNOWN TYPE BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13MENU) <- "NUMBER OF MENINGOCOCCAL-UNKNOWN SEROGROUP SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13TDAP_POST10) <- "NUMBER OF TDAP SHOTS SINCE AGE 10 YEARS AND BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_N13TDAP_POST7) <- "NUMBER OF TDAP SHOTS SINCE AGE 7 YEARS AND BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13TDP) <- "NUMBER OF TD/TDAP-CONTAINING SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13TDP_11) <- "NUMBER OF TD-ONLY SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13TDP_14) <- "NUMBER OF TDAP-ONLY SHOTS BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_N13TDP_15) <- "NUMBER OF TD/TDAP-CONTAINING SHOTS OF UNKNOWN TYPE BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_N13TDP_POST10) <- "NUMBER OF TD/TDAP-CONTAINING SHOTS SINCE AGE 10 YEARS AND BY AGE 13 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMHPV) <- "NUMBER OF HUMAN PAPILLOMAVIRUS SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMHPV_4V) <- "NUMBER OF HPV-GARDASIL (4vHPV) SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMHPV_9V) <- "NUMBER OF HPV-GARDASIL 9 (9vHPV) SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMHPV_CV) <- "NUMBER OF HPV-CERVARIX SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_NUMHPV_HP) <- "NUMBER OF HPV SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMHPV_UV) <- "NUMBER OF HPV-GARDASIL, UNKNOWN VALENCY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMMEN) <- "NUMBER OF MENINGOCOCCAL SEROGROUP ACWY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMMEN_80) <- "NUMBER OF MENINGOCOCCAL MCV4 SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMMEN_81) <- "NUMBER OF MENINGOCOCCAL MPSV4 SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_NUMMEN_82) <- "NUMBER OF MENINGOCOCCAL SEROGROUP ACWY SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMMENB) <- "NUMBER OF MENINGOCOCCAL SEROGROUP B SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMMENB_BB) <- "NUMBER OF MENINGOCOCCAL MENB-4C SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMMENB_BT) <- "NUMBER OF MENINGOCOCCAL MENB-FHPB SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMMENB_BU) <- "NUMBER OF MENINGOCOCCAL SEROGROUP B SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_NUMMENU) <- "NUMBER OF MENINGOCOCCAL-UNKNOWN SEROGROUP SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMTDAP_POST10) <- "NUMBER OF TDAP SHOTS SINCE AGE 10 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMTDAP_POST7) <- "NUMBER OF TDAP SHOTS SINCE AGE 7 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMTDP) <- "NUMBER OF TD/TDAP-CONTAINING SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMTDP_11) <- "NUMBER OF TD-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_NUMTDP_14) <- "NUMBER OF TDAP-ONLY SHOTS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMTDP_15) <- "NUMBER OF TD/TDAP-CONTAINING SHOTS OF UNKNOWN TYPE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_NUMTDP_POST10) <- "NUMBER OF TD/TDAP-CONTAINING SHOTS SINCE AGE 10 YEARS DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_U13HPV) <- "UP-TO-DATE FLAG (PROV INFO): 1+ HUMAN PAPILLOMAVIRUS SHOT BEFORE AGE 13 YEARS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_U13HPV3) <- "UP-TO-DATE FLAG (PROV INFO): 3+ HUMAN PAPILLOMAVIRUS SHOTS BEFORE AGE 13 YEARS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_U13113) <- "UP-TO-DATE FLAG (PROV INFO): 1:1:3 SERIES BEFORE AGE 13 YEARS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_U13MEN) <- "UP-TO-DATE FLAG (PROV INFO): 1+ MENINGOCOCCAL SEROGROUP ACWY SHOT BEFORE AGE 13 YEARS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_U13TD) <- "UP-TO-DATE FLAG (PROV INFO): 1+ TD/TDAP-CONTAINING SHOT BEFORE AGE 13 YEARS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_U13TDAP) <- "UP-TO-DATE FLAG (PROV INFO): 1+ TDAP-ONLY SHOT SINCE AGE 10 YEARS AND BEFORE AGE 13 YEARS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_U13TDAP7) <- "UP-TO-DATE FLAG (PROV INFO): 1+ TDAP-ONLY SHOT SINCE AGE 7 YEARS AND BEFORE AGE 13 YEARS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_UTDHPV) <- "UP-TO-DATE FLAG (PROV INFO): 1+ HUMAN PAPILLOMAVIRUS SHOT, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDHPV_15) <- "UP-TO-DATE FLAG (PROV INFO): 3+ HUMAN PAPILLOMAVIRUS SHOTS, OR 2+ HUMAN PAPILLOMAVIRUS SHOTS WITH FIRST SHOT RECEIVED BEFORE AGE 15, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDHPV_15INT) <- "UP-TO-DATE FLAG (PROV INFO): 3+ HUMAN PAPILLOMAVIRUS SHOTS, OR 2+ HUMAN PAPILLOMAVIRUS SHOTS WITH FIRST SHOT RECEIVED BEFORE AGE 15 AND INTERVAL BETWEEN 1ST AND 2ND SHOTS AT LEAST 5 MONTHS-4 DAYS, EXCLUDING ANY VACCIN
ATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDHPV_9V) <- "UP-TO-DATE FLAG (PROV INFO): 1+ HUMAN PAPILLOMAVIRUS SHOT OF TYPE GARDASIL 9 (9vHPV), EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDHPV11) <- "UP-TO-DATE FLAG (PROV INFO): 1 HUMAN PAPILLOMAVIRUS SHOT GIVEN 1+ SHOT, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_UTDHPV12) <- "UP-TO-DATE FLAG (PROV INFO): 2 HUMAN PAPILLOMAVIRUS SHOTS GIVEN 1+ SHOT, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDHPV13) <- "UP-TO-DATE FLAG (PROV INFO): 3+ HUMAN PAPILLOMAVIRUS SHOTS GIVEN 1+ SHOT, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDHPV2) <- "UP-TO-DATE FLAG (PROV INFO): 2+ HUMAN PAPILLOMAVIRUS SHOTS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDHPV2_9V) <- "UP-TO-DATE FLAG (PROV INFO): 2+ HUMAN PAPILLOMAVIRUS SHOTS OF TYPE GARDASIL 9 (9vHPV), EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDHPV3) <- "UP-TO-DATE FLAG (PROV INFO): 3+ HUMAN PAPILLOMAVIRUS SHOTS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_UTDHPV3_9V) <- "UP-TO-DATE FLAG (PROV INFO): 3+ HUMAN PAPILLOMAVIRUS SHOTS OF TYPE GARDASIL 9 (9vHPV), EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDHPV3C) <- "UP-TO-DATE FLAG (PROV INFO): HPV CONDITIONAL COMPLETION RATE, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDHPV3C_15INT) <- "UP-TO-DATE FLAG (PROV INFO): HPV CONDITIONAL COMPLETION RATE, INCLUDING COMPLETION VIA 3-SHOT OR 2-SHOT SERIES, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDHPV3C_9V) <- "UP-TO-DATE FLAG (PROV INFO): HPV CONDITIONAL COMPLETION RATE, COUNTING ONLY SHOTS OF TYPE GARDASIL 9 (9vHPV), EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDMEN) <- "UP-TO-DATE FLAG (PROV INFO): 1+ MENINGOCOCCAL SEROGROUP ACWY SHOT, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_UTDMENACWY) <- "UP-TO-DATE FLAG (PROV INFO): 1+ MENINGOCOCCAL SEROGROUP ACWY-CONJUGATE SHOT OR MENINGOCOCCAL SEROGROUP ACWY-UNKNOWN TYPE SHOT, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDTD) <- "UP-TO-DATE FLAG (PROV INFO): 1+ TD/TDAP-CONTAINING SHOT, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDTDAP) <- "UP-TO-DATE FLAG (PROV INFO): 1+ TDAP-ONLY SHOT SINCE AGE 10 YEARS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDTDAP7) <- "UP-TO-DATE FLAG (PROV INFO): 1+ TDAP-ONLY SHOT SINCE AGE 7 YEARS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$P_UTDTDP_POST10) <- "UP-TO-DATE FLAG (PROV INFO): 1+ TD/TDAP-CONTAINING SHOT SINCE AGE 10 YEARS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."

label(NISTEENPUF18$P_UTDTD_POST10) <- "UP-TO-DATE FLAG (PROV INFO): 1+ TD-ONLY SHOT SINCE AGE 10 YEARS, EXCLUDING ANY VACCINATIONS AFTER THE RDD INTERVIEW DATE."
label(NISTEENPUF18$HPV_AGE1) <- "AGE IN YEARS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #1"
label(NISTEENPUF18$HPV_AGE2) <- "AGE IN YEARS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #2"
label(NISTEENPUF18$HPV_AGE3) <- "AGE IN YEARS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #3"
label(NISTEENPUF18$HPV_AGE4) <- "AGE IN YEARS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #4"

label(NISTEENPUF18$HPV_AGE5) <- "AGE IN YEARS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #5"
label(NISTEENPUF18$HPV_AGE6) <- "AGE IN YEARS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #6"
label(NISTEENPUF18$HPV_AGE7) <- "AGE IN YEARS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #7"
label(NISTEENPUF18$HPV_AGE8) <- "AGE IN YEARS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #8"
label(NISTEENPUF18$HPV_AGE9) <- "AGE IN YEARS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #9"

label(NISTEENPUF18$HPV_DAGE1) <- "AGE IN DAYS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #1"
label(NISTEENPUF18$HPV_DAGE2) <- "AGE IN DAYS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #2"
label(NISTEENPUF18$HPV_DAGE3) <- "AGE IN DAYS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #3"
label(NISTEENPUF18$HPV_DAGE4) <- "AGE IN DAYS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #4"
label(NISTEENPUF18$HPV_DAGE5) <- "AGE IN DAYS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #5"

label(NISTEENPUF18$HPV_DAGE6) <- "AGE IN DAYS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #6"
label(NISTEENPUF18$HPV_DAGE7) <- "AGE IN DAYS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #7"
label(NISTEENPUF18$HPV_DAGE8) <- "AGE IN DAYS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #8"
label(NISTEENPUF18$HPV_DAGE9) <- "AGE IN DAYS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #9"
label(NISTEENPUF18$HPV_MAGE1) <- "AGE IN MONTHS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #1"

label(NISTEENPUF18$HPV_MAGE2) <- "AGE IN MONTHS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #2"
label(NISTEENPUF18$HPV_MAGE3) <- "AGE IN MONTHS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #3"
label(NISTEENPUF18$HPV_MAGE4) <- "AGE IN MONTHS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #4"
label(NISTEENPUF18$HPV_MAGE5) <- "AGE IN MONTHS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #5"
label(NISTEENPUF18$HPV_MAGE6) <- "AGE IN MONTHS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #6"

label(NISTEENPUF18$HPV_MAGE7) <- "AGE IN MONTHS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #7"
label(NISTEENPUF18$HPV_MAGE8) <- "AGE IN MONTHS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #8"
label(NISTEENPUF18$HPV_MAGE9) <- "AGE IN MONTHS OF PROV-REPORTED HUMAN PAPILLOMAVIRUS SHOT #9"
label(NISTEENPUF18$MEN_AGE1) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #1"
label(NISTEENPUF18$MEN_AGE2) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #2"

label(NISTEENPUF18$MEN_AGE3) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #3"
label(NISTEENPUF18$MEN_AGE4) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #4"
label(NISTEENPUF18$MEN_AGE5) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #5"
label(NISTEENPUF18$MEN_AGE6) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #6"
label(NISTEENPUF18$MEN_AGE7) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #7"

label(NISTEENPUF18$MEN_AGE8) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #8"
label(NISTEENPUF18$MEN_AGE9) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #9"
label(NISTEENPUF18$MEN_DAGE1) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #1"
label(NISTEENPUF18$MEN_DAGE2) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #2"
label(NISTEENPUF18$MEN_DAGE3) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #3"

label(NISTEENPUF18$MEN_DAGE4) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #4"
label(NISTEENPUF18$MEN_DAGE5) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #5"
label(NISTEENPUF18$MEN_DAGE6) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #6"
label(NISTEENPUF18$MEN_DAGE7) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #7"
label(NISTEENPUF18$MEN_DAGE8) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #8"

label(NISTEENPUF18$MEN_DAGE9) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #9"
label(NISTEENPUF18$MEN_MAGE1) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #1"
label(NISTEENPUF18$MEN_MAGE2) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #2"
label(NISTEENPUF18$MEN_MAGE3) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #3"
label(NISTEENPUF18$MEN_MAGE4) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #4"

label(NISTEENPUF18$MEN_MAGE5) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #5"
label(NISTEENPUF18$MEN_MAGE6) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #6"
label(NISTEENPUF18$MEN_MAGE7) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #7"
label(NISTEENPUF18$MEN_MAGE8) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #8"
label(NISTEENPUF18$MEN_MAGE9) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP ACWY SHOT #9"

label(NISTEENPUF18$MENB_AGE1) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #1"
label(NISTEENPUF18$MENB_AGE2) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #2"
label(NISTEENPUF18$MENB_AGE3) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #3"
label(NISTEENPUF18$MENB_AGE4) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #4"
label(NISTEENPUF18$MENB_AGE5) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #5"

label(NISTEENPUF18$MENB_AGE6) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #6"
label(NISTEENPUF18$MENB_AGE7) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #7"
label(NISTEENPUF18$MENB_AGE8) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #8"
label(NISTEENPUF18$MENB_AGE9) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #9"
label(NISTEENPUF18$MENB_DAGE1) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #1"

label(NISTEENPUF18$MENB_DAGE2) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #2"
label(NISTEENPUF18$MENB_DAGE3) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #3"
label(NISTEENPUF18$MENB_DAGE4) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #4"
label(NISTEENPUF18$MENB_DAGE5) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #5"
label(NISTEENPUF18$MENB_DAGE6) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #6"

label(NISTEENPUF18$MENB_DAGE7) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #7"
label(NISTEENPUF18$MENB_DAGE8) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #8"
label(NISTEENPUF18$MENB_DAGE9) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #9"
label(NISTEENPUF18$MENB_MAGE1) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #1"
label(NISTEENPUF18$MENB_MAGE2) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #2"

label(NISTEENPUF18$MENB_MAGE3) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #3"
label(NISTEENPUF18$MENB_MAGE4) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #4"
label(NISTEENPUF18$MENB_MAGE5) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #5"
label(NISTEENPUF18$MENB_MAGE6) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #6"
label(NISTEENPUF18$MENB_MAGE7) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #7"

label(NISTEENPUF18$MENB_MAGE8) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #8"
label(NISTEENPUF18$MENB_MAGE9) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL SEROGROUP B SHOT #9"
label(NISTEENPUF18$MENU_AGE1) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #1"
label(NISTEENPUF18$MENU_AGE2) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #2"
label(NISTEENPUF18$MENU_AGE3) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #3"

label(NISTEENPUF18$MENU_AGE4) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #4"
label(NISTEENPUF18$MENU_AGE5) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #5"
label(NISTEENPUF18$MENU_AGE6) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #6"
label(NISTEENPUF18$MENU_AGE7) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #7"
label(NISTEENPUF18$MENU_AGE8) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #8"

label(NISTEENPUF18$MENU_AGE9) <- "AGE IN YEARS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #9"
label(NISTEENPUF18$MENU_DAGE1) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #1"
label(NISTEENPUF18$MENU_DAGE2) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #2"
label(NISTEENPUF18$MENU_DAGE3) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #3"
label(NISTEENPUF18$MENU_DAGE4) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #4"

label(NISTEENPUF18$MENU_DAGE5) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #5"
label(NISTEENPUF18$MENU_DAGE6) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #6"
label(NISTEENPUF18$MENU_DAGE7) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #7"
label(NISTEENPUF18$MENU_DAGE8) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #8"
label(NISTEENPUF18$MENU_DAGE9) <- "AGE IN DAYS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #9"

label(NISTEENPUF18$MENU_MAGE1) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #1"
label(NISTEENPUF18$MENU_MAGE2) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #2"
label(NISTEENPUF18$MENU_MAGE3) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #3"
label(NISTEENPUF18$MENU_MAGE4) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #4"
label(NISTEENPUF18$MENU_MAGE5) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #5"

label(NISTEENPUF18$MENU_MAGE6) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #6"
label(NISTEENPUF18$MENU_MAGE7) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #7"
label(NISTEENPUF18$MENU_MAGE8) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #8"
label(NISTEENPUF18$MENU_MAGE9) <- "AGE IN MONTHS OF PROV-REPORTED MENINGOCOCCAL-UNKNOWN SEROGROUP SHOT #9"
label(NISTEENPUF18$TDP_AGE1) <- "AGE IN YEARS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #1"

label(NISTEENPUF18$TDP_AGE2) <- "AGE IN YEARS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #2"
label(NISTEENPUF18$TDP_AGE3) <- "AGE IN YEARS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #3"
label(NISTEENPUF18$TDP_AGE4) <- "AGE IN YEARS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #4"
label(NISTEENPUF18$TDP_AGE5) <- "AGE IN YEARS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #5"
label(NISTEENPUF18$TDP_AGE6) <- "AGE IN YEARS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #6"

label(NISTEENPUF18$TDP_AGE7) <- "AGE IN YEARS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #7"
label(NISTEENPUF18$TDP_AGE8) <- "AGE IN YEARS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #8"
label(NISTEENPUF18$TDP_AGE9) <- "AGE IN YEARS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #9"
label(NISTEENPUF18$TDP_DAGE1) <- "AGE IN DAYS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #1"
label(NISTEENPUF18$TDP_DAGE2) <- "AGE IN DAYS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #2"

label(NISTEENPUF18$TDP_DAGE3) <- "AGE IN DAYS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #3"
label(NISTEENPUF18$TDP_DAGE4) <- "AGE IN DAYS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #4"
label(NISTEENPUF18$TDP_DAGE5) <- "AGE IN DAYS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #5"
label(NISTEENPUF18$TDP_DAGE6) <- "AGE IN DAYS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #6"
label(NISTEENPUF18$TDP_DAGE7) <- "AGE IN DAYS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #7"

label(NISTEENPUF18$TDP_DAGE8) <- "AGE IN DAYS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #8"
label(NISTEENPUF18$TDP_DAGE9) <- "AGE IN DAYS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #9"
label(NISTEENPUF18$TDP_MAGE1) <- "AGE IN MONTHS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #1"
label(NISTEENPUF18$TDP_MAGE2) <- "AGE IN MONTHS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #2"
label(NISTEENPUF18$TDP_MAGE3) <- "AGE IN MONTHS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #3"

label(NISTEENPUF18$TDP_MAGE4) <- "AGE IN MONTHS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #4"
label(NISTEENPUF18$TDP_MAGE5) <- "AGE IN MONTHS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #5"
label(NISTEENPUF18$TDP_MAGE6) <- "AGE IN MONTHS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #6"
label(NISTEENPUF18$TDP_MAGE7) <- "AGE IN MONTHS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #7"
label(NISTEENPUF18$TDP_MAGE8) <- "AGE IN MONTHS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #8"

label(NISTEENPUF18$TDP_MAGE9) <- "AGE IN MONTHS OF PROV-REPORTED TD/TDAP-CONTAINING SHOT #9"
label(NISTEENPUF18$XHPVTY1) <- "HUMAN PAPILLOMAVIRUS VACCINATION #1 TYPE CODE"
label(NISTEENPUF18$XHPVTY2) <- "HUMAN PAPILLOMAVIRUS VACCINATION #2 TYPE CODE"
label(NISTEENPUF18$XHPVTY3) <- "HUMAN PAPILLOMAVIRUS VACCINATION #3 TYPE CODE"
label(NISTEENPUF18$XHPVTY4) <- "HUMAN PAPILLOMAVIRUS VACCINATION #4 TYPE CODE"

label(NISTEENPUF18$XHPVTY5) <- "HUMAN PAPILLOMAVIRUS VACCINATION #5 TYPE CODE"
label(NISTEENPUF18$XHPVTY6) <- "HUMAN PAPILLOMAVIRUS VACCINATION #6 TYPE CODE"
label(NISTEENPUF18$XHPVTY7) <- "HUMAN PAPILLOMAVIRUS VACCINATION #7 TYPE CODE"
label(NISTEENPUF18$XHPVTY8) <- "HUMAN PAPILLOMAVIRUS VACCINATION #8 TYPE CODE"
label(NISTEENPUF18$XHPVTY9) <- "HUMAN PAPILLOMAVIRUS VACCINATION #9 TYPE CODE"

label(NISTEENPUF18$XMENBTY1) <- "MENINGOCOCCAL SEROGROUP B VACCINATION #1 TYPE CODE"
label(NISTEENPUF18$XMENBTY2) <- "MENINGOCOCCAL SEROGROUP B VACCINATION #2 TYPE CODE"
label(NISTEENPUF18$XMENBTY3) <- "MENINGOCOCCAL SEROGROUP B VACCINATION #3 TYPE CODE"
label(NISTEENPUF18$XMENBTY4) <- "MENINGOCOCCAL SEROGROUP B VACCINATION #4 TYPE CODE"
label(NISTEENPUF18$XMENBTY5) <- "MENINGOCOCCAL SEROGROUP B VACCINATION #5 TYPE CODE"

label(NISTEENPUF18$XMENBTY6) <- "MENINGOCOCCAL SEROGROUP B VACCINATION #6 TYPE CODE"
label(NISTEENPUF18$XMENBTY7) <- "MENINGOCOCCAL SEROGROUP B VACCINATION #7 TYPE CODE"
label(NISTEENPUF18$XMENBTY8) <- "MENINGOCOCCAL SEROGROUP B VACCINATION #8 TYPE CODE"
label(NISTEENPUF18$XMENBTY9) <- "MENINGOCOCCAL SEROGROUP B VACCINATION #9 TYPE CODE"
label(NISTEENPUF18$XMENTY1) <- "MENINGOCOCCAL SEROGROUP ACWY VACCINATION #1 TYPE CODE"

label(NISTEENPUF18$XMENTY2) <- "MENINGOCOCCAL SEROGROUP ACWY VACCINATION #2 TYPE CODE"
label(NISTEENPUF18$XMENTY3) <- "MENINGOCOCCAL SEROGROUP ACWY VACCINATION #3 TYPE CODE"
label(NISTEENPUF18$XMENTY4) <- "MENINGOCOCCAL SEROGROUP ACWY VACCINATION #4 TYPE CODE"
label(NISTEENPUF18$XMENTY5) <- "MENINGOCOCCAL SEROGROUP ACWY VACCINATION #5 TYPE CODE"
label(NISTEENPUF18$XMENTY6) <- "MENINGOCOCCAL SEROGROUP ACWY VACCINATION #6 TYPE CODE"

label(NISTEENPUF18$XMENTY7) <- "MENINGOCOCCAL SEROGROUP ACWY VACCINATION #7 TYPE CODE"
label(NISTEENPUF18$XMENTY8) <- "MENINGOCOCCAL SEROGROUP ACWY VACCINATION #8 TYPE CODE"
label(NISTEENPUF18$XMENTY9) <- "MENINGOCOCCAL SEROGROUP ACWY VACCINATION #9 TYPE CODE"
label(NISTEENPUF18$XTDPTY1) <- "TD/TDAP-CONTAINING VACCINATION #1 TYPE CODE"
label(NISTEENPUF18$XTDPTY2) <- "TD/TDAP-CONTAINING VACCINATION #2 TYPE CODE"

label(NISTEENPUF18$XTDPTY3) <- "TD/TDAP-CONTAINING VACCINATION #3 TYPE CODE"
label(NISTEENPUF18$XTDPTY4) <- "TD/TDAP-CONTAINING VACCINATION #4 TYPE CODE"
label(NISTEENPUF18$XTDPTY5) <- "TD/TDAP-CONTAINING VACCINATION #5 TYPE CODE"
label(NISTEENPUF18$XTDPTY6) <- "TD/TDAP-CONTAINING VACCINATION #6 TYPE CODE"
label(NISTEENPUF18$XTDPTY7) <- "TD/TDAP-CONTAINING VACCINATION #7 TYPE CODE"

label(NISTEENPUF18$XTDPTY8) <- "TD/TDAP-CONTAINING VACCINATION #8 TYPE CODE"
label(NISTEENPUF18$XTDPTY9) <- "TD/TDAP-CONTAINING VACCINATION #9 TYPE CODE"
label(NISTEENPUF18$INS_STAT2_I) <- "INSURANCE STATUS (PRIVATE ONLY/ANY MEDICAID/OTHER INSURANCE/UNINSURED): IMPUTED"
label(NISTEENPUF18$INS_BREAK_I) <- "CONTINUITY OF INSURANCE COVERAGE SINCE AGE 11: IMPUTED"

############################################################################
# Step 5:   CREATE A PERMANENT R DATASET                                   #
############################################################################

save(NISTEENPUF18, file=paste(PUF, "/NISTEENPUF18.RData", sep=""))

############################################################################
# Step 6:   ASSIGN FORMATS                                                 #
#	  FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES	IN R           #
############################################################################

# commenting out since I don't need all variables factored--some of this code
# will be copied to another script

# NISTEENPUF18$PDAT2 <- factor(NISTEENPUF18$PDAT2, levels=ADEQlevels, labels=ADEQlabels)
# NISTEENPUF18$ASTHMA <- factor(NISTEENPUF18$ASTHMA, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$CKUP_11_12 <- factor(NISTEENPUF18$CKUP_11_12, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$CKUP_LAST <- factor(NISTEENPUF18$CKUP_LAST, levels=CKUPLASTlevels, labels=CKUPLASTlabels)
# NISTEENPUF18$CPOX_AGER <- factor(NISTEENPUF18$CPOX_AGER, levels=CPOX_Rlevels, labels=CPOX_Rlabels)
# 
# NISTEENPUF18$CPOX_HAD <- factor(NISTEENPUF18$CPOX_HAD, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_ANY <- factor(NISTEENPUF18$HPVI_ANY, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_INTENTR <- factor(NISTEENPUF18$HPVI_INTENTR, levels=LIKELYlevels, labels=LIKELYlabels)
# NISTEENPUF18$HPVI_REAS_1 <- factor(NISTEENPUF18$HPVI_REAS_1, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_10 <- factor(NISTEENPUF18$HPVI_REAS_10, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$HPVI_REAS_11 <- factor(NISTEENPUF18$HPVI_REAS_11, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_12 <- factor(NISTEENPUF18$HPVI_REAS_12, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_13 <- factor(NISTEENPUF18$HPVI_REAS_13, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_14 <- factor(NISTEENPUF18$HPVI_REAS_14, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_15 <- factor(NISTEENPUF18$HPVI_REAS_15, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$HPVI_REAS_16 <- factor(NISTEENPUF18$HPVI_REAS_16, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_17 <- factor(NISTEENPUF18$HPVI_REAS_17, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_18 <- factor(NISTEENPUF18$HPVI_REAS_18, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_19 <- factor(NISTEENPUF18$HPVI_REAS_19, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_2 <- factor(NISTEENPUF18$HPVI_REAS_2, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$HPVI_REAS_20 <- factor(NISTEENPUF18$HPVI_REAS_20, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_21 <- factor(NISTEENPUF18$HPVI_REAS_21, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_22 <- factor(NISTEENPUF18$HPVI_REAS_22, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_23 <- factor(NISTEENPUF18$HPVI_REAS_23, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_24 <- factor(NISTEENPUF18$HPVI_REAS_24, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$HPVI_REAS_25 <- factor(NISTEENPUF18$HPVI_REAS_25, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_26 <- factor(NISTEENPUF18$HPVI_REAS_26, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_27 <- factor(NISTEENPUF18$HPVI_REAS_27, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_28 <- factor(NISTEENPUF18$HPVI_REAS_28, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_29 <- factor(NISTEENPUF18$HPVI_REAS_29, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$HPVI_REAS_3 <- factor(NISTEENPUF18$HPVI_REAS_3, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_30 <- factor(NISTEENPUF18$HPVI_REAS_30, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_31 <- factor(NISTEENPUF18$HPVI_REAS_31, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_5 <- factor(NISTEENPUF18$HPVI_REAS_5, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_REAS_6 <- factor(NISTEENPUF18$HPVI_REAS_6, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$HPVI_REAS_9 <- factor(NISTEENPUF18$HPVI_REAS_9, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$HPVI_RECOM <- factor(NISTEENPUF18$HPVI_RECOM, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$IMM_ANY <- factor(NISTEENPUF18$IMM_ANY, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_ANY <- factor(NISTEENPUF18$MEN_ANY, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_1 <- factor(NISTEENPUF18$MEN_REAS_1, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$MEN_REAS_10 <- factor(NISTEENPUF18$MEN_REAS_10, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_11 <- factor(NISTEENPUF18$MEN_REAS_11, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_12 <- factor(NISTEENPUF18$MEN_REAS_12, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_13 <- factor(NISTEENPUF18$MEN_REAS_13, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_14 <- factor(NISTEENPUF18$MEN_REAS_14, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$MEN_REAS_15 <- factor(NISTEENPUF18$MEN_REAS_15, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_16 <- factor(NISTEENPUF18$MEN_REAS_16, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_17 <- factor(NISTEENPUF18$MEN_REAS_17, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_18 <- factor(NISTEENPUF18$MEN_REAS_18, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_19 <- factor(NISTEENPUF18$MEN_REAS_19, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$MEN_REAS_2 <- factor(NISTEENPUF18$MEN_REAS_2, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_20 <- factor(NISTEENPUF18$MEN_REAS_20, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_21 <- factor(NISTEENPUF18$MEN_REAS_21, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_22 <- factor(NISTEENPUF18$MEN_REAS_22, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_23 <- factor(NISTEENPUF18$MEN_REAS_23, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$MEN_REAS_24 <- factor(NISTEENPUF18$MEN_REAS_24, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_25 <- factor(NISTEENPUF18$MEN_REAS_25, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_3 <- factor(NISTEENPUF18$MEN_REAS_3, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_4 <- factor(NISTEENPUF18$MEN_REAS_4, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_5 <- factor(NISTEENPUF18$MEN_REAS_5, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$MEN_REAS_6 <- factor(NISTEENPUF18$MEN_REAS_6, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$MEN_REAS_7 <- factor(NISTEENPUF18$MEN_REAS_7, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$NOSCHOOLR <- factor(NISTEENPUF18$NOSCHOOLR, levels=NOSCHRlevels, labels=NOSCHRlabels)
# NISTEENPUF18$RISK_EVER <- factor(NISTEENPUF18$RISK_EVER, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$RISK_HH <- factor(NISTEENPUF18$RISK_HH, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$RISK_NOW <- factor(NISTEENPUF18$RISK_NOW, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_ANY <- factor(NISTEENPUF18$TET_ANY, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_1 <- factor(NISTEENPUF18$TET_REAS_1, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_10 <- factor(NISTEENPUF18$TET_REAS_10, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_11 <- factor(NISTEENPUF18$TET_REAS_11, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$TET_REAS_12 <- factor(NISTEENPUF18$TET_REAS_12, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_13 <- factor(NISTEENPUF18$TET_REAS_13, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_14 <- factor(NISTEENPUF18$TET_REAS_14, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_15 <- factor(NISTEENPUF18$TET_REAS_15, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_16 <- factor(NISTEENPUF18$TET_REAS_16, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$TET_REAS_17 <- factor(NISTEENPUF18$TET_REAS_17, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_18 <- factor(NISTEENPUF18$TET_REAS_18, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_19 <- factor(NISTEENPUF18$TET_REAS_19, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_2 <- factor(NISTEENPUF18$TET_REAS_2, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_20 <- factor(NISTEENPUF18$TET_REAS_20, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$TET_REAS_21 <- factor(NISTEENPUF18$TET_REAS_21, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_22 <- factor(NISTEENPUF18$TET_REAS_22, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_23 <- factor(NISTEENPUF18$TET_REAS_23, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_24 <- factor(NISTEENPUF18$TET_REAS_24, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_25 <- factor(NISTEENPUF18$TET_REAS_25, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$TET_REAS_26 <- factor(NISTEENPUF18$TET_REAS_26, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_3 <- factor(NISTEENPUF18$TET_REAS_3, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_4 <- factor(NISTEENPUF18$TET_REAS_4, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_5 <- factor(NISTEENPUF18$TET_REAS_5, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$TET_REAS_7 <- factor(NISTEENPUF18$TET_REAS_7, levels=YNDKRFlevels, labels=YNDKRFlabels)
# 
# NISTEENPUF18$VISITS <- factor(NISTEENPUF18$VISITS, levels=HVSTSlevels, labels=HVSTSlabels)
# NISTEENPUF18$AGEGRP_M_I <- factor(NISTEENPUF18$AGEGRP_M_I, levels=AGEGRP_Mlevels, labels=AGEGRP_Mlabels)
# NISTEENPUF18$C1R <- factor(NISTEENPUF18$C1R, levels=C1Rlevels, labels=C1Rlabels)
# NISTEENPUF18$C5R <- factor(NISTEENPUF18$C5R, levels=C5Rlevels, labels=C5Rlabels)
# NISTEENPUF18$CEN_REG <- factor(NISTEENPUF18$CEN_REG, levels=CENREGlevels, labels=CENREGlabels)
# 
# NISTEENPUF18$CHILDNM <- factor(NISTEENPUF18$CHILDNM, levels=CHILDNMFlevels, labels=CHILDNMFlabels)
# NISTEENPUF18$EDUC1 <- factor(NISTEENPUF18$EDUC1, levels=EDUC4_Mlevels, labels=EDUC4_Mlabels)
# NISTEENPUF18$EDUC_TR <- factor(NISTEENPUF18$EDUC_TR, levels=EDUC_TRlevels, labels=EDUC_TRlabels)
# NISTEENPUF18$INCPOV1 <- factor(NISTEENPUF18$INCPOV1, levels=INCPOVlevels, labels=INCPOVlabels)
# NISTEENPUF18$INCQ298A <- factor(NISTEENPUF18$INCQ298A, levels=INCQ298Alevels, labels=INCQ298Alabels)
# 
# NISTEENPUF18$I_HISP_K <- factor(NISTEENPUF18$I_HISP_K, levels=YNDKRFlevels, labels=YNDKRFlabels)
# NISTEENPUF18$LANGUAGE <- factor(NISTEENPUF18$LANGUAGE, levels=LANGUAGElevels, labels=LANGUAGElabels)
# NISTEENPUF18$MARITAL2 <- factor(NISTEENPUF18$MARITAL2, levels=MAR_PUF2_levels, labels=MAR_PUF2_labels)
# NISTEENPUF18$MOBIL_I <- factor(NISTEENPUF18$MOBIL_I, levels=MOBILlevels, labels=MOBILlabels)
# NISTEENPUF18$NUM_PHONE <- factor(NISTEENPUF18$NUM_PHONE, levels=NUM_PHONlevels, labels=NUM_PHONlabels)
# 
# NISTEENPUF18$NUM_CELLS_HH <- factor(NISTEENPUF18$NUM_CELLS_HH, levels=NUM_PHONlevels, labels=NUM_PHONlabels)
# NISTEENPUF18$NUM_CELLS_PARENTS <- factor(NISTEENPUF18$NUM_CELLS_PARENTS, levels=NUM_PHONlevels, labels=NUM_PHONlabels)
# NISTEENPUF18$RACEETHK <- factor(NISTEENPUF18$RACEETHK, levels=RACEETHKlevels, labels=RACEETHKlabels)
# NISTEENPUF18$RACE_K <- factor(NISTEENPUF18$RACE_K, levels=RACE_PUFlevels, labels=RACE_PUFlabels)
# NISTEENPUF18$RENT_OWN <- factor(NISTEENPUF18$RENT_OWN, levels=RENTOWNlevels, labels=RENTOWNlabels)
# 
# NISTEENPUF18$SEX <- factor(NISTEENPUF18$SEX, levels=SEXlevels, labels=SEXlabels)
# NISTEENPUF18$ESTIAPT18 <- factor(NISTEENPUF18$ESTIAPT18, levels=ESTIAPT18Flevels, labels=ESTIAPT18Flabels)
# NISTEENPUF18$EST_GRANT <- factor(NISTEENPUF18$EST_GRANT, levels=ESTGRANTFlevels, labels=ESTGRANTFlabels)
# NISTEENPUF18$STATE <- factor(NISTEENPUF18$STATE, levels=STATElevels, labels=STATElabels)
# NISTEENPUF18$D6R <- factor(NISTEENPUF18$D6R, levels=D6Rlevels, labels=D6Rlabels)
# 
# NISTEENPUF18$D7 <- factor(NISTEENPUF18$D7, levels=CONSENTlevels, labels=CONSENTlabels)
# NISTEENPUF18$NUM_PROVR <- factor(NISTEENPUF18$NUM_PROVR, levels=D6Rlevels, labels=D6Rlabels)
# NISTEENPUF18$N_PRVR <- factor(NISTEENPUF18$N_PRVR, levels=D6Rlevels, labels=D6Rlabels)
# NISTEENPUF18$FACILITY <- factor(NISTEENPUF18$FACILITY, levels=FACILSUMlevels, labels=FACILSUMlabels)
# NISTEENPUF18$REGISTRY <- factor(NISTEENPUF18$REGISTRY, levels=REGISTRYlevels, labels=REGISTRYlabels)
# 
# NISTEENPUF18$VFC_ORDER <- factor(NISTEENPUF18$VFC_ORDER, levels=REGISTRYlevels, labels=REGISTRYlabels)
# NISTEENPUF18$WELLCHILD <- factor(NISTEENPUF18$WELLCHILD, levels=IHQYNDKlevels, labels=IHQYNDKlabels)
# NISTEENPUF18$P_U13HPV <- factor(NISTEENPUF18$P_U13HPV, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_U13HPV3 <- factor(NISTEENPUF18$P_U13HPV3, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_U13113 <- factor(NISTEENPUF18$P_U13113, levels=UTDlevels, labels=UTDlabels)
# 
# NISTEENPUF18$P_U13MEN <- factor(NISTEENPUF18$P_U13MEN, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_U13TD <- factor(NISTEENPUF18$P_U13TD, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_U13TDAP <- factor(NISTEENPUF18$P_U13TDAP, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_U13TDAP7 <- factor(NISTEENPUF18$P_U13TDAP7, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDHPV <- factor(NISTEENPUF18$P_UTDHPV, levels=UTDlevels, labels=UTDlabels)
# 
# NISTEENPUF18$P_UTDHPV_15 <- factor(NISTEENPUF18$P_UTDHPV_15, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDHPV_15INT <- factor(NISTEENPUF18$P_UTDHPV_15INT, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDHPV_9V <- factor(NISTEENPUF18$P_UTDHPV_9V, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDHPV11 <- factor(NISTEENPUF18$P_UTDHPV11, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDHPV12 <- factor(NISTEENPUF18$P_UTDHPV12, levels=UTDlevels, labels=UTDlabels)
# 
# NISTEENPUF18$P_UTDHPV13 <- factor(NISTEENPUF18$P_UTDHPV13, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDHPV2 <- factor(NISTEENPUF18$P_UTDHPV2, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDHPV2_9V <- factor(NISTEENPUF18$P_UTDHPV2_9V, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDHPV3 <- factor(NISTEENPUF18$P_UTDHPV3, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDHPV3_9V <- factor(NISTEENPUF18$P_UTDHPV3_9V, levels=UTDlevels, labels=UTDlabels)
# 
# NISTEENPUF18$P_UTDHPV3C <- factor(NISTEENPUF18$P_UTDHPV3C, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDHPV3C_15INT <- factor(NISTEENPUF18$P_UTDHPV3C_15INT, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDHPV3C_9V <- factor(NISTEENPUF18$P_UTDHPV3C_9V, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDMEN <- factor(NISTEENPUF18$P_UTDMEN, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDMENACWY <- factor(NISTEENPUF18$P_UTDMENACWY, levels=UTDlevels, labels=UTDlabels)
# 
# NISTEENPUF18$P_UTDTD <- factor(NISTEENPUF18$P_UTDTD, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDTDAP <- factor(NISTEENPUF18$P_UTDTDAP, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDTDAP7 <- factor(NISTEENPUF18$P_UTDTDAP7, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDTDP_POST10 <- factor(NISTEENPUF18$P_UTDTDP_POST10, levels=UTDlevels, labels=UTDlabels)
# NISTEENPUF18$P_UTDTD_POST10 <- factor(NISTEENPUF18$P_UTDTD_POST10, levels=UTDlevels, labels=UTDlabels)
# 
# NISTEENPUF18$XHPVTY1 <- factor(NISTEENPUF18$XHPVTY1, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XHPVTY2 <- factor(NISTEENPUF18$XHPVTY2, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XHPVTY3 <- factor(NISTEENPUF18$XHPVTY3, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XHPVTY4 <- factor(NISTEENPUF18$XHPVTY4, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XHPVTY5 <- factor(NISTEENPUF18$XHPVTY5, levels=TYPElevels, labels=TYPElabels)
# 
# NISTEENPUF18$XHPVTY6 <- factor(NISTEENPUF18$XHPVTY6, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XHPVTY7 <- factor(NISTEENPUF18$XHPVTY7, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XHPVTY8 <- factor(NISTEENPUF18$XHPVTY8, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XHPVTY9 <- factor(NISTEENPUF18$XHPVTY9, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENBTY1 <- factor(NISTEENPUF18$XMENBTY1, levels=TYPElevels, labels=TYPElabels)
# 
# NISTEENPUF18$XMENBTY2 <- factor(NISTEENPUF18$XMENBTY2, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENBTY3 <- factor(NISTEENPUF18$XMENBTY3, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENBTY4 <- factor(NISTEENPUF18$XMENBTY4, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENBTY5 <- factor(NISTEENPUF18$XMENBTY5, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENBTY6 <- factor(NISTEENPUF18$XMENBTY6, levels=TYPElevels, labels=TYPElabels)
# 
# NISTEENPUF18$XMENBTY7 <- factor(NISTEENPUF18$XMENBTY7, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENBTY8 <- factor(NISTEENPUF18$XMENBTY8, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENBTY9 <- factor(NISTEENPUF18$XMENBTY9, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENTY1 <- factor(NISTEENPUF18$XMENTY1, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENTY2 <- factor(NISTEENPUF18$XMENTY2, levels=TYPElevels, labels=TYPElabels)
# 
# NISTEENPUF18$XMENTY3 <- factor(NISTEENPUF18$XMENTY3, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENTY4 <- factor(NISTEENPUF18$XMENTY4, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENTY5 <- factor(NISTEENPUF18$XMENTY5, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENTY6 <- factor(NISTEENPUF18$XMENTY6, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENTY7 <- factor(NISTEENPUF18$XMENTY7, levels=TYPElevels, labels=TYPElabels)
# 
# NISTEENPUF18$XMENTY8 <- factor(NISTEENPUF18$XMENTY8, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XMENTY9 <- factor(NISTEENPUF18$XMENTY9, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XTDPTY1 <- factor(NISTEENPUF18$XTDPTY1, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XTDPTY2 <- factor(NISTEENPUF18$XTDPTY2, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XTDPTY3 <- factor(NISTEENPUF18$XTDPTY3, levels=TYPElevels, labels=TYPElabels)
# 
# NISTEENPUF18$XTDPTY4 <- factor(NISTEENPUF18$XTDPTY4, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XTDPTY5 <- factor(NISTEENPUF18$XTDPTY5, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XTDPTY6 <- factor(NISTEENPUF18$XTDPTY6, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XTDPTY7 <- factor(NISTEENPUF18$XTDPTY7, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$XTDPTY8 <- factor(NISTEENPUF18$XTDPTY8, levels=TYPElevels, labels=TYPElabels)
# 
# NISTEENPUF18$XTDPTY9 <- factor(NISTEENPUF18$XTDPTY9, levels=TYPElevels, labels=TYPElabels)
# NISTEENPUF18$INS_STAT2_I <- factor(NISTEENPUF18$INS_STAT2_I, levels=INS_STAT2_Ilevels, labels=INS_STAT2_Ilabels)
# NISTEENPUF18$INS_BREAK_I <- factor(NISTEENPUF18$INS_BREAK_I, levels=INS_BREAK_Ilevels, labels=INS_BREAK_Ilabels)
# 
# ##########################################################################
# # STEP 7:   CONTENTS AND STATISTICAL ESTIMATES(FREQUENCY) EXAMPLE        #
# ##########################################################################
# 
# #---CONTENTS---#
# NISTEENPUF18.CONTENTS <- contents(NISTEENPUF18)$contents
# 
# print(NISTEENPUF18.CONTENTS)
# 
# #IN CASE THAT THE R CONSOLE CANNOT DISPLAY WHOLE CONTENTS,
# #YOU CAN SAVE CONTENTS INTO A FILE
# #write.table(NISTEENPUF18.CONTENTS, file=paste(PUF,"/file-name",sep=""))
# 
# #---UNWEIGHTED FREQUENCY---#
# unwt_freq <- function(UNWT.VAR){#FUNCTION TO PRINT UNWEIGHTED FREQUENCIES
# 
# unwt.tab <- wtd.table(UNWT.VAR, weights= NULL, type='table')
# unwtd.freq <- data.frame(cbind(
# unwt.tab, round(unwt.tab/sum(unwt.tab)*100,2),
# cumsum(unwt.tab), cumsum(round(unwt.tab/sum(unwt.tab)*100,2))))
# names(unwtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
# unwtd.title <- paste('2018 NIS-TEEN PUBLIC USE FILE', 'UNWEIGHTED FREQUENCIES', label(UNWT.VAR), sep="\n")
# label(unwtd.freq) <- unwtd.title
# 
# print(unwtd.freq)
# }
# 
# UNWT.VAR <- NISTEENPUF18$AGE	#INPUT A VARIABLE OF INTEREST
# unwt_freq(UNWT.VAR)
# 
# #---WEIGHTED FREQUENCY---#
# WT <- NISTEENPUF18$RDDWT_C	#INPUT A WEIGHT VARIABLE
# WT.VAR <- NISTEENPUF18$AGE 	#INPUT A VARIABLE OF INTEREST
# 
# wt.tab <- wtd.table(WT.VAR, weights= WT, type='table')
# wtd.freq <- data.frame(cbind(
# wt.tab, round(wt.tab/sum(wt.tab)*100,2),
# cumsum(wt.tab), cumsum(round(wt.tab/sum(wt.tab)*100,2))))
# names(wtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
# wtd.title <- paste('2018 NIS-TEEN PUBLIC USE FILE', 'WEIGHTED FREQUENCIES', label(WT.VAR), sep="\n")
# label(wtd.freq) <- wtd.title
# 
# print(wtd.freq)
