# ui portion of R shiny app -----------------------------------------------

body <- navbarPage(tags$head(includeCSS(here(data_dir, "Style/navbarpage_style.css"))),
                   introjsUI(),
                   theme = shinytheme("flatly"), collapsible = TRUE,
                   title = div(img(src="https://uw-s3-cdn.s3.us-west-2.amazonaws.com/wp-content/uploads/sites/98/2014/09/07214416/W-Logo_White.png",width= "73px", height="45px"),  strong(toupper("Global Vaccine Index Dashboard"))),
                   tabPanel("Visualizations",
                            sidebarPanel(
                              h4(strong("Vaccination Improvement Potential (VIP) Index Ranking Table")),
                              sliderInput("year", "Year", value = 2019, min = 1990, max = 2019, step=1, sep = "", 
                                          animate = TRUE),
                              fluidRow(column(8,radioButtons("sdi_group_present","2019 SDI Group", choices = c("All"="all","Low" ="low","Medium" = "medium","High" = "high"),inline = TRUE)),
                                       column(2,
                                              #tags$i
                                              # class = "glyphicon glyphicon-info-sign", 
                                              # style = "color:#2c3e50;;",
                                              # title = "The Socio-demographic Index (SDI) is a summary measure that identifies where countries sit on the spectrum of development."
                                              #))),
                                              dropMenu(
                                                circleButton(label = "What is SDI?","What is SDI?", inputId='sdiinfo',icon = icon('info')),
                                                h4(strong('SDI')),
                                                h5('The Socio-demographic Index (SDI) is a summary measure that identifies where countries sit on the spectrum of development.'),
                                                placement = "bottom",
                                                arrow = TRUE),
                                              style='text-align:center',
                                              class = 'rightAlign')),
                              selectInput("region_table", "Regions", selected = NULL, choices = c("All",unique(index_results$region))),
                              tags$style(HTML('table.dataTable tr.selected td, table.dataTable td.selected {background-color: #92c9e8 !important;}')),
                              DT::dataTableOutput("table")),
                            mainPanel(
                              div(class="outer",absolutePanel(fixed=FALSE, width = "100%", 
                                                              draggable = FALSE, height = "100%",
                                                              tags$style(type="text/css",
                                                                         ".shiny-output-error { visibility: hidden; }",
                                                                         ".shiny-output-error:before { visibility: hidden; }"
                                                              ),
                                                              tabsetPanel(id = "t1",
                                                                          tabPanel("Vaccination Improvement",value="t_sdi",
                                                                                   fluidRow(column(6, " ", style='padding:10px;')),
                                                                                   fluidRow(column(width = 9,h4(strong(textOutput("yeartitle")),style='text-align:left')),
                                                                                            column(width = 3,div(switchInput(
                                                                                              inputId = "view",
                                                                                              # label = "Display",
                                                                                              onLabel = "Show Map",
                                                                                              offLabel = "Show Table",
                                                                                              value = FALSE,
                                                                                              labelWidth = "50px")))
                                                                                            # column(width = 2, div(actionButton(inputId = "view", label = "Table"),
                                                                                            #                       actionButton(inputId = "map", label = "Map")))
                                                                                            ),
                                                                                   conditionalPanel("!input.view", 
                                                                                                    fluidRow(column(12, " ", style='padding:3px;')),
                                                                                                    fluidRow(column(10, radioButtons(inputId = "show",label = NULL,
                                                                                                                                     choices = c("Vaccination Improvement Potential (VIP) Index","VIP Index Component"),
                                                                                                                                     selected = "Vaccination Improvement Potential (VIP) Index",
                                                                                                                                     inline = TRUE)), 
                                                                                                             column(2,
                                                                                                                    dropMenu(
                                                                                                                      circleButton(label = "", inputId='info',icon = icon('info')),
                                                                                                                      h4(strong('Index Mapper')),
                                                                                                                      h5('The Vaccine Improvement Index assesses a country’s potential to improve its immunization rates.'),
                                                                                                                      h5("A higher number (or darker shading on the map) indicates a better score."),
                                                                                                                      placement = "bottom",
                                                                                                                      arrow = TRUE))),
                                                                                                    conditionalPanel("input.show == 'Vaccination Improvement Potential (VIP) Index'",
                                                                                                                     fluidRow(column(12, " ", style='padding:3px;')),
                                                                                                                     fluidRow(column(12,plotlyOutput("index_map",height = "40vh")),column(1,"")),
                                                                                                                     fluidRow(column(width = 12, "Select locations in left VIP Index Ranking Table for comparison",
                                                                                                                                     style='font-family:Avenir, Helvetica;font-size:30;text-align:center')),
                                                                                                                     fluidRow(column(10,''),column(2,
                                                                                                                                                   dropMenu(
                                                                                                                                                     circleButton(label = "", inputId='info2',icon = icon('info')),
                                                                                                                                                     h4(strong('Time Series of Vaccination Improvement Potential (VIP) Index')),
                                                                                                                                                     h5('The index value is estimated yearly between 1990 and 2019, in order to track improvement or change over time. '),
                                                                                                                                                     placement = "bottom",
                                                                                                                                                     arrow = TRUE))),
                                                                                                                     fluidRow(column(12, plotlyOutput("index_trend_plot_multi",height = "30vh"))),column(1,"")),
                                                                                                    fluidRow(column(12, " ", style='padding:2px;')),
                                                                                                    conditionalPanel("input.show == 'VIP Index Component'",
                                                                                                                     #fluidRow(column(4,selectInput("indicators", "Indicator:",choices=c("SDI","Development Assistance Per Total Health Spending Categorical","Total Health Spending per Person","Government Health Spending per Total Health Spending",
                                                                                                                     #                                                                  "HAQI","Corruption Perception Index","Skilled Attendants at Birth","Immigrant Population (%)","Urbanicity (%)","Agreement Vaccines are Safe",
                                                                                                                     #                                                                 "Agreement Vaccines are Important","Agreement Vaccines are Effective"),width = "500px")),
                                                                                                                     fluidRow(column(5,selectInput("indicators", "Indicator:",choices=c("Socio-demographic Index","Eligibility to Receive DAH","Total Health Spending per Person","Government Health Spending per Total Health Spending",
                                                                                                                                                                                        "Development Assistance per Person","HAQI","Corruption Perception Index","Skilled Attendants at Birth","Immigrant Population (%)","Urbanicity (%)"),width = "500px"))),
                                                                                                                     fluidRow(column(11,plotlyOutput("indicator_map",height = "43vh")),column(1,"")),
                                                                                                                     column(width = 12, "Select location in left VIP Index Ranking Table for comparison",
                                                                                                                            style='font-family:Avenir, Helvetica;font-size:30;text-align:center;padding:2px; padding-bottom: 20px'),
                                                                                                                     fluidRow(column(11, plotlyOutput("indicator_trend_plot_multi",height = "27vh")),column(1,""))
                                                                                                    )),
                                                                                   conditionalPanel("input.view",
                                                                                                    fluidRow(column(11, DT::dataTableOutput("indextable")),column(1,"")))),
                                                                          tabPanel("Vaccination Trends", value = "t_vac",
                                                                                   fluidRow(column(width = 11,h4(strong(htmlOutput("content_vac"))))),
                                                                                   fluidRow(column(width = 10, "Select location in left VIP Ranking table",
                                                                                                   style='font-family:Avenir, Helvetica;font-size:30;text-align:left'),
                                                                                            column(2,
                                                                                                   dropMenu(
                                                                                                     circleButton(label = "", inputId='info3',icon = icon('info')),
                                                                                                     h4(strong('Vaccination Trends')),
                                                                                                     h5('Recommended vaccinations and the date they began to be used can differ between countries. This visual shows how vaccination coverage has changed over time in a particular location.'),
                                                                                                     placement = "bottom",
                                                                                                     arrow = TRUE))),
                                                                                   fluidRow(column(8, " ", style='padding:10px;')),
                                                                                   radioButtons("vaccine_plot","Plot type:", choices = c("Time Series of Vaccine Coverage" ="line_trend","Single Year Vaccine Coverage"="bar_plot"),inline = TRUE),
                                                                                   fluidRow(column(11,plotlyOutput("all_vaccine_plot",height = "50vh")),column(1,""))),
                                                                          tabPanel("Mortality & Disability Trends",value = "d_vac",
                                                                                   fluidRow(column(width = 11,h4(strong(htmlOutput("content_dis"))))),
                                                                                   fluidRow(column(width = 10, "Select location in left VIP Index Ranking Table",
                                                                                                   style='font-family:Avenir, Helvetica;font-size:30;text-align:left'),
                                                                                            column(2,
                                                                                                   dropMenu(
                                                                                                     circleButton(label = "", inputId='info4',icon = icon('info')),
                                                                                                     h4(strong('Mortality and Disability Trends')),
                                                                                                     h5('This graphic shows how the number of deaths or number of people infected have changed between the years 1990 to 2019. The diseases or disabilities presented on this graph can all be prevented with a vaccine administered at the appropriate time.'),
                                                                                                     placement = "bottom",
                                                                                                     arrow = TRUE))),
                                                                                   radioButtons("disease_estimate","Choose y-axis:", choices = c("Number Value"="number_val","Percent Value" ="percent_val","Rate Value" = "rate_val"),inline = TRUE),
                                                                                   plotlyOutput("all_disease_plot", height = "35vh"),
                                                                                   fluidRow(column(10, " ", style='padding:30px;'),
                                                                                            column(2,
                                                                                                   dropMenu(
                                                                                                     circleButton(label = "", inputId='info5',icon = icon('info')),
                                                                                                     h4(strong('Times Series of Number of Years Lived with Disability')),
                                                                                                     h5('Can also be considered total years lived with less than ideal health. This measure takes into account prevelance and duration of illnesses.'),
                                                                                                     placement = "bottom",
                                                                                                     arrow = TRUE))),
                                                                                   plotlyOutput("all_disability_plot", height = "35vh")),
                                                                          tabPanel(paste0("Vaccination & Corresponding Disease Trends"),value="vac_dis_tab",
                                                                                   fluidRow(column(12,h4(strong(htmlOutput("content_vac_dis"))))),
                                                                                   fluidRow(column(10,selectInput("vaccinations", "Vaccination:",choices=NULL)),
                                                                                            column(2,
                                                                                                   dropMenu(
                                                                                                     circleButton(label = "", inputId='info6',icon = icon('info')),
                                                                                                     h4(strong('Vaccination and Disease Trends')),
                                                                                                     h5('This graphic compares vaccination rates and the death rate from the diseases that vaccines help prevent.'),
                                                                                                     placement = "bottom",
                                                                                                     arrow = TRUE))),
                                                                                   fluidRow(column(12,plotlyOutput("selected_vac_dis_plot",height = "40vh"))),
                                                                                   fluidRow(
                                                                                     column(3,
                                                                                            h4("BCG"),
                                                                                            helpText("Bacillus Calmette–Guérin"),
                                                                                            DT::dataTableOutput("BCGtable")),
                                                                                     column(3,
                                                                                            h4("DTP1 & DTP3"),
                                                                                            helpText("Diphtheria, tetanus, pertussis"),
                                                                                            DT::dataTableOutput("DTPtable")),
                                                                                     column(2,
                                                                                            h4("HepB3"),
                                                                                            helpText("Hepatitis B"),
                                                                                            DT::dataTableOutput("HepB3table")), 
                                                                                     column(2,
                                                                                            h4("MCV1 & MCV2"),
                                                                                            helpText("Measles"),
                                                                                            DT::dataTableOutput("MCVtable")), 
                                                                                     column(1,
                                                                                            h4("RotaC"),
                                                                                            helpText("Rotavirus"),
                                                                                            DT::dataTableOutput("RotaCtable"))
                                                                                   )),
                                                                          tabPanel("Data Explorer",
                                                                                   fluidRow(column(5, " ", style='padding:5px;')),
                                                                                   fluidRow(column(9, radioButtons("dataset","Choose Dataset", choices = c("Improvement Index"= "improvement index","Vaccine Trends" = "vaccine trends","Disease Trends" = "disease trends","Data Dictionary" = "data dictionary"),inline = TRUE)),
                                                                                            column(3, style = "margin-top: 10px;",div(downloadButton("download","Download Raw Data"),style='float:right'))),
                                                                                   fluidRow(column(width = 9, "Download custom datasets from the variables that were used to create visuals on the previous tabs. ",
                                                                                                   style='font-family:Avenir, Helvetica;font-size:30;text-align:left')),
                                                                                   fluidRow(column(12,DT::dataTableOutput("alldatatable") %>% withSpinner(color="#4b2e83")))
                                                                          )
                                                              ),
                                                              tags$head(tags$style('ul.nav.nav-tabs { overflow-y: hidden; display: flex;}')
                                                              ), 
                              ))))
                   ,
                   tabPanel("Reports",
                            mainPanel(
                              tabsetPanel(tabPanel("Community Leaders",
                                                   tags$div(id = "reportsPage", 
                                                            h4(id = "reportsHeader","The Role of Community Leaders to Reduce Vaccine Hesitancy"),
                                                            h5(id = "reportsText", "Vaccine hesitancy is a growing public health concern defined by an individual’s refusal or delayed acceptance of a readily available vaccine. Vaccine hesitancy has many contributing causes including but not limited to, historical, political, and socio-cultural factors; addressing hesitancy is a key factor in successfully increasing vaccination coverage globally Engaging and educating trusted community leaders has been explored as a strategy to reduce vaccine hesitancy and increase a community’s vaccine uptake1. The WHO has created a framework called “Human-centered design for tailoring immunization programs”, in which they stress community engagement as a key pillar for building trust between healthcare systems and individuals 2. The COVID-19 pandemic has served as a large-scale experiment in quickly vaccinating communities against SARS-Cov-2. This surge for vaccination required the development of strategies to reduce vaccine hesitancy around the globe, particularly in underserved and vulnerable communities. Two organizations in particular, Breakthrough Action – a partnership led by Johns Hopkins Center for Communication Programs, and The Partnership for Healthy Cities supported by Bloomberg Philanthropies in partnership with the World Health Organization (WHO) and Vital Strategies have sponsored programs in cities and communities across the globe with the goal of educating and engaging community leaders to decrease vaccine hesitancy. The Partnership for Healthy Cities has supported community lead programs in 18 cities across the world with a focus on educating local leaders on the importance of vaccination against COVID-19 3. To illustrate this further a few campaigns associated with Breakthrough Action and the Partnership for Healthy Cities will be highlighted."),
                                                            img(src="Community_Leaders_Picture1.jpg", width= "700px"),
                                                            # plot(10:1), 
                                                            # fluidRow(
                                                            #   class = "top-row",
                                                            #   box(
                                                            #     width = 2,
                                                            #     class = "card-hexagon",
                                                            #     img(src = "Data/www/Community_Leaders_Picture1.jpg"),
                                                            #     div("Health Ranking", class = "card-hexagon-title")
                                                            #   ),
                                                            #   # ... 
                                                            #   box(
                                                            #     width = 2,
                                                            #     class = "card-hexagon",
                                                            #     div(style = "height: 100px; width: 100px",
                                                            #         img(src = "Data/www/Community_Leaders_Picture1.jpg"),
                                                            #         div(
                                                            #           class = "card-hexagon-title",
                                                            #           tags$a(
                                                            #             "Leafdown",
                                                            #             tags$i(class = "fas fa-xs fa-external-link-alt"),
                                                            #             href = "https://github.com/hoga-it/leafdown",
                                                            #             target = "_blank",
                                                            #             style = "color: white;"
                                                            #           )
                                                            #         )
                                                            #     )
                                                            #   )
                                                            # ),
                                                            
                                                            h6("Credit: Vital Strategies"),
                                                            h4(id = "reportsHeader", "Buenos Aires, Argentina: The peer-to-peer “Butterfly Effect” project vaccinates people experiencing homelessness"),
                                                            h5(id = "reportsText", "In Buenos Aires a campaign was created to increase vaccine coverage of the unhoused population within the city. The unhoused due to various socioeconomic and health factors have high levels of mistrust towards health systems and healthcare personnel. To address this, the city formed a group of 44 formerly unhoused people to develop an outreach program based on one-to-one communication outreach strategies. The campaign successfully vaccinated 10,000 people over the course of 4 months and provided new insights into future outreach programs. The researchers found that reducing barriers to getting vaccinated such as the need for completing online forms or showing ID led to a greater vaccine uptake among the unhoused population 4. See the link below for the full story from Vital Strategies blog."),
                                                            h4(id = "reportsHeader", "Engaging Religious Leaders to Boost COVID-19 Vaccination"),
                                                            img(src="Community_Leaders_Picture2.jpg", width= "700px"),
                                                            h6("Malawi's Bishop Martin Mtumbuka. Credit: Lusayo Banda"),
                                                            h5(id = "reportsText", "Johns Hopkins Center for Communications Programs (CCP) has worked alongside religious leaders in Africa to combat vaccine misinformation that has proliferated throughout many communities. Johns Hopkins CCP has worked in Malawi, Liberia, and Nigeria to engage and educate faith leaders in local communities. In Malawi 144 leaders were given education sessions on COVID-19 prevention and vaccination. This training helps faith leaders create campaigns to increase vaccine demand in their local communities. In Nigeria, a two-day forum was hosted in which state and local health officials discussed common rumors and myths surrounding the vaccines and gave leaders talking points they could bring back with them to better address concerns surrounding vaccine safety.  In Liberia a vaccine ambassador program was established to train a range of influential community leaders to be educators on COVID-19 prevention and vaccination. The ambassadors have gone on to host community engagement events and talk on local radio stations 5."),
                                                            h4(id = "reportsHeader", "Battling Covid-19 Vaccine Misinformation Through Targeted Community Dialogues"),
                                                            img(src=here("Data/www/Community_Leaders_Picture3.png"), width= "700px"),
                                                            h6("Credit: Breakthrough ACTION"),
                                                            h5(id = "reportsText", "In Guinea, Breakthrough Action partnered with the National Agency for Health Security of Guinea to create programs to combat misinformation and rumors surrounding the pandemic and vaccines. Community dialogue sessions took in place in which Public Health Officials were able to gain feedback from local leaders about their community’s special needs and conditions regarding vaccine hesitancy while also equipping leaders with tools to combat these hesitancies. These sessions were well received and many leaders felt that they had been given the resources needed to better educate their communities about the nature of the pandemic as well as the importance of getting vaccinated 6."),
                                                            h4(id = "reportsHeader", "Key Lessons"),
                                                            h5(id = "reportsText", "These campaigns addressing COVID-19 prevention and vaccine hesitancy in local communities can provide more broadly applicable lessons for combatting hesitancy and increasing vaccine dosage demand in communities. Understanding and using existent community structures and leaders can enable Public Health Officials to make efficient usage of resources and to better understand the material reality of the on the ground conditions inside these communities.  Community engagement meetings can serve as a way for Public Health Officials to continuously monitor and understand trends in public opinion and test out new ways of engaging with the population on these issues while receiving real time feedback. Training community leaders to combat myths surrounding vaccines can be an effective strategy for reaching community members with an already trusted voice. It has long been a mistake of Western Public Health Agencies to not engage enough with community leaders and instead take a paternalistic approach of global health that minimizes that opportunity for local voices to have a say in how Global Health funds are being utilized. Both programs seek to change this old paradigm by participating in active conversations with communities and their leaders, enabling them to take a more community-based approach to Public Health programs. Equipping members of underserved communities to become advocates in their own communities can create a “social butterfly effect” which spreads vaccination talking points throughout the community, creating an organic and eventually self-perpetuating community-based conversation about vaccination. With vaccine hesitancy on the rise in many parts of the globe it is paramount that leaders in Global Health take note of these successful campaigns to increase vaccine demand in underserved communities across the global and they we seek to apply these lessons going into the future."),
                                                            h4(id = "reportsHeader", "References"),
                                                            h5("1.	Dubé, E. et al. Vaccine hesitancy. Hum Vaccin Immunother 9, 1763–1773 (2013).",
                                                               tags$br(), tags$br(),
                                                               "2.	World Health Organization & Fund (UNICEF), U. N. C. Human-centred design for tailoring immunization programmes. (World Health Organization, 2022).",
                                                               tags$br(), tags$br(),
                                                               "3.	The Partnership for Healthy Cities supports COVID-19 Vaccine Outreach Efforts of 18 Cities in Africa, Asia, and Latin America. https://www.who.int/news/item/06-05-2021-the-partnership-for-health-cities-supports-covid-19-vaccine-outreach-efforts-of-18-cities-in-africa-asia-and-latin-america.",
                                                               tags$br(), tags$br(),
                                                               "4.	Trusted Voices for COVID-19: Engaging community leaders to overcome vaccine hesitancy. Vital Strategies https://www.vitalstrategies.org/vital-stories-trusted-voices-for-covid-19-engaging-community-leaders-to-overcome-vaccine-hesitancy/.",
                                                               tags$br(), tags$br(),
                                                               "5.	Engaging Religious Leaders to Boost COVID-19 Vaccination. Johns Hopkins Center for Communication Programs https://ccp.jhu.edu/2022/05/02/religious-leaders-covid/ (2022).",
                                                               tags$br(), tags$br(),
                                                               "6.	meeichild. Battling COVID-19 Vaccine Misinformation Through Targeted Community Dialogues. Breakthrough ACTION and RESEARCH https://breakthroughactionandresearch.org/battling-covid-19-vaccine-misinformation-through-targeted-community-dialogues/ (2022)."
                                                               )
                                                            )
                                                   ),
                                          tabPanel("Canada",
                                                   tags$div(id = "reportsPage",
                                                            h2(id = "reportsHeader", "Canada"),
                                                            h5(id = "reportsText", "Canada is one of the top 28 richest nations and boasts one of the best healthcare systems that in the world. Despite this, its childhood vaccination coverage is only around 84% which is far behind other developed countries such as the UK and the USA. (1) It was also found that approximately 20% of the population is vaccine apprehensive, and approximately 5% of the populace holds anti-vaccination sentiments. (2)", 
                                                               tags$br(), tags$br(), "High rates of immunization are critical for preventing the spread of many infectious diseases. The immunizations for children that are recommended include the DPTP-Hib, Rotavirus, Pneumococcal, Meningococcal, MMR, Varicella, Hepatitis B, dTap, and HPV vaccines. (3)"),
                                                            h4(id = "reportsHeader", "Challenges in vaccine coverage"),
                                                            h5(id = "reportsText", "Low vaccine coverage rates in Canada may be ascribed to parents' reluctance to vaccinate their children due to a lack of clarity and misinformation. An interesting pattern observed is that parents with high levels of education, namely those with postgraduate degrees, frequently lack faith in the efficacy of vaccinations and are worried more about potential for  adverse reactions, such as anaphylaxis or paralysis caused by vaccines. On the other hand, parents of children with education levels below secondary school frequently know little about immunization programs and worry about their potential side effects. (4) Another factor that contributed to incomplete immunization (children not receiving  all of the recommended doses) was the parents' marital status. The children of single parents often did not receive the recommended number of doses of vaccines. (5) It's also crucial to recognize that philosophical and religious opposition to immunizations still exists and contributes to around 10% of vaccine hesitancy. (6)",
                                                               tags$br(), tags$br(), "A significant problem is frequently posed by the heterogeneity of immunization programs in each of Canada's territories. People frequently have questions about whether or not the neighborhood hospitals or clinics provide free vaccinations. Additionally, a lot of individuals are worried about the potential out-of-pocket cost and are often uninformed of the free immunization program that the Canadian government provides.", 
                                                               tags$br(), tags$br(), "Finally, the COVID outbreak in 2019 also contributed to a decline in immunization rates by forcing a temporary suspension of immunization campaigns. (7) However, in the years 2020 and 2021, this was improved by giving infants shorter appointments and by adhering to guidelines including wearing PPE kits and screening for COVID-19."),
                                                            h4(id = "reportsHeader", "Ways to improve vaccine coverage: "),
                                                            h5(id = "reportsText", "According to one study, Canadians most frequently regarded the sources of information given by their healthcare practitioners as reliable. (8) As a result, regular health checkups should include educating patients on the benefits of vaccination in order to foster a positive attitude toward vaccination. Another study discovered that pharmacists could be trained to educate people about vaccination, its side effects, and how to obtain them. (8) Raising awareness about the actual negative effects of vaccines aids in the prevention of the spread of false information about vaccines, as uninformed people frequently believe that the vaccine failed to work and caused their symptoms.",
                                                               tags$br(), tags$br(), "Additionally, in the era of infodemics on social media, it would also be beneficial if videos, reels, and podcasts of pediatricians talking about vaccinations are promoted more on social media, so people could have access to high-quality unbiased information.",
                                                               tags$br(), tags$br(), "As healthcare professionals, it would beneficial if a set of dedicated staff could handle immunization requests. This would cut down on hospital wait times, which are a major obstacle for parents. The same group of nurses should also be in charge of sending out reminders through messages and calls. It has been observed that this tailored immunization delivery has increased immunization rates. (10) The significant issue of incomplete immunization among children could be addressed by extending the hours of local clinics. In addition, it would be helpful if the health system made better attempts to inform parents about the next date for immunizations of their children and ensured that the parents followed the schedule.",
                                                               tags$br(), tags$br(), "When parents refuse vaccination for their children due to religious beliefs, it is critical that healthcare workers respect those beliefs. However, healthcare professionals could inform them with respect of the significance of immunizations. Vaccination coverage is also high in cultures that promote the collective benefits of vaccinations. It would be extremely beneficial for health care professionals to educate parents on the significance of herd immunity, explaining that by immunizing their children, they are protecting immunocompromised children. Thereby inspiring them to grow a strong sense of social responsibility.",
                                                               tags$br(), tags$br(), "Thus, in order to increase vaccination coverage for childhood vaccines and close immunity gaps, prosocial nudges, awareness about the importance of vaccination, increased access, and promotion of reliable sources of vaccination information, would be required. (11) Listed below are few trusted sources about vaccination provided by the Canadian government:",
                                                               tags$br(), tags$ul(tags$li(tags$a("https://caringforkids.cps.ca/handouts/immunization/vaccination_and_your_child", target = "_blank", href = "https://caringforkids.cps.ca/handouts/immunization/vaccination_and_your_child")),
                                                                                  tags$li(tags$a("https://immunize.ca/", target = "_blank", href = "https://immunize.ca/")),
                                                                                  tags$li(tags$a("https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19/vaccines.html", target = "_blank", href = "https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19/vaccines.html")),
                                                                                  )),
                                                            h4(id = "reportsHeader", "References"),
                                                            h5("1. UNICEF Office of Research, Innocenti Report Card 11 (2013) Child well-being in rich countries: A comparative overview. <www.unicef-irc.org/publications/pdf/rc11_eng.pdf> ",
                                                               tags$br(), tags$br(),
                                                               "2. Stratoberdha D, Gobis B, Ziemczonek A, Yuen J, Giang A, Zed PJ. Barriers to adult vaccination in Canada: A qualitative systematic review. Canadian Pharmacists Journal / Revue des Pharmaciens du Canada. June 2022. doi:10.1177/17151635221090212 ",
                                                               tags$br(), tags$br(),
                                                               "https://immunize.ca/",
                                                               tags$br(), tags$br(),
                                                               "4. Carpiano RM, Polonijo AN, Gilbert N, Cantin L, Dubé E. Socioeconomic status differences in parental immunization attitudes and child immunization in Canada: Findings from the 2013 Childhood National Immunization Coverage Survey (CNICS). Prev Med. 2019; 123:278-287. doi: 10.1016/j.ypmed.2019.03.033",
                                                               tags$br(), tags$br(),
                                                               "5. Boulianne N, Deceuninck G, Duval B, Lavoie F, Dionne M, Carsley J, Valiquette L, Rochette L, De Serres G. Why are some children incompletely vaccinated at the age of 2? Can J Public Health 2003; 94:218-23; PMID:12790498",
                                                               tags$br(), tags$br(),
                                                               "6. Gilbert NL, Gilmour H, Wilson SE, Cantin L. Determinants of non-vaccination and incomplete vaccination in Canadian toddlers. Hum Vaccin Immunother. 2017;13(6):1-7. doi:10.1080/21645515.2016.1277847",
                                                               tags$br(), tags$br(),
                                                               "7.MacDonald SE, Paudel YR, Kiely M, et al. Impact of the COVID-19 pandemic on vaccine coverage for early childhood vaccines in Alberta, Canada: a population-based retrospective cohort study. BMJ Open.m2022;12(1):e055968. Published 2022 Jan 25. doi:10.1136/bmjopen-2021-055968 ",
                                                               tags$br(), tags$br(),
                                                               "8.  Brenner RA, Simons-Morton BG, Bhaskar B, et al. Prevalence and   predictors of immunization inner-city infants: a birth cohort study. Pediatrics. 2001;108(3):661–670.",
                                                               tags$br(), tags$br(),
                                                               "9. Lisenby KM, Patel KN, Uichanco MT. The role of pharmacists in addressing vaccine hesitancy and the measles outbreak. J Pharm Pract. 2021;34(1):127-32. ",
                                                               tags$br(), tags$br(),
                                                               "10. Zimmerman RK, Nowalk MP, Raymund M, et al. Tailored interventions to increase influenza vaccination in neighborhood health centers serving the disadvantaged. Am J Pub Health. 2003;93(10):1699–1705", 
                                                               tags$br(), tags$br(),
                                                               "11. Mah CL, Guttmann A, McGeer A, Krahn M, Deber RB. Compulsory school-entry vaccination laws and exemptions: who is opting out in ontario and why does it matter? Healthc Policy. 2010;5(4):37-46.",  
                                                               tags$br(), tags$br(),
                                                               "12. Scheifele DW, Halperin SA, Bettinger JA. Childhood immunization rates in Canada are too low: UNICEF. Paediatr Child Health. 2014;19(5):237-238. doi:10.1093/pch/19.5.237",
                                                               tags$br(), tags$br(),
                                                               "13. Betsch, C., Böhm, R., Korn, L. et al. On the benefits of explaining herd immunity in vaccine advocacy. Nat Hum Behav 1, 0056 (2017). https://doi.org/10.1038/s41562-017-0056")  
                                                            )
                                                   ),
                                          tabPanel("Document 1",
                                                   # tags$iframe(embed(src="/www/Canada Childhood Vaccination FInal.pdf", width= "100%", height="400px"))
                                                   tags$iframe(style = "height:400px; width:100%; scrolling=yes", src = here("Data/www/Canada_Childhood_Vaccination_Final.pdf"))
                                                   )
                                          )
                            )),
                   tabPanel("Sample Report",
                            sidebarPanel(
                              h4(strong("Sample Report: for Nigeria")),
                              fluidRow(column(6, " ", style='padding:70px;')),
                              fluidRow(column(12,h5(strong(textOutput("report_nig_title"))))),
                              fluidRow(column(6, " ", style='padding:10px;')),
                              fluidRow(column(12,textOutput("report_nig_body"))),
                              fluidRow(column(6, " ", style='padding:90px;')),
                              tags$head(tags$style("{color: #0060bf; font-size: 20px;}")),
                              downloadButton(
                                outputId = "report",
                                label = "Download Report"
                              ),
                              width = 4),
                            mainPanel(
                              tabsetPanel(id="t2",
                                          tabPanel("Comparison",value = "comp_index",
                                                   fluidRow(column(8, " ", style='padding:20px;')),
                                                   fluidRow(column(4,radioButtons("sdi_group_present_comp","2019 SDI Group", choices = c("All"="all","Low" ="low","Medium" = "medium","High" = "high"),selected="low",inline = TRUE)),
                                                            column(4,selectInput("region", "Regions", choices = unique(index_results$region))),
                                                            column(4,selectInput(
                                                              inputId = "my_multi",
                                                              label = "Search Country :",
                                                              choices = unique(merged_data_for_vacii_sdi$location),
                                                              selected = "Nigeria",
                                                              selectize = TRUE,
                                                              multiple=TRUE))),
                                                   fluidRow(column(8, " ", style='padding:20px;')),
                                                   fluidRow(column(12, plotlyOutput("index_trend_plot_com",height = "40vh"))),column(1,"")),
                                          tabPanel("Vaccination Trends",value = "report_vt",
                                                   fluidRow(column(width = 11,h4(strong("Nigeria")))),
                                                   fluidRow(column(8, " ", style='padding:10px;')),
                                                   fluidRow(column(11,plotlyOutput("nigeria_vaccine_plot",height = "55vh")),column(1,""))),
                                          tabPanel("Mortality and Disability Trends",value = "report_md",
                                                   fluidRow(column(width = 11,h4(strong("Nigeria")))),
                                                   fluidRow(column(8, " ", style='padding:10px;')),
                                                   fluidRow(column(12,plotlyOutput("nigeria_disability_plot", height = "45vh")))),
                                          tabPanel("Vaccination and Corresponding Diseases Trends",value = "report_vcdt",
                                                   fluidRow(column(width = 11,h4(strong("Nigeria")))),
                                                   fluidRow(column(width = 11,h5(strong("Selected Vaccination: MCV1")))),
                                                   fluidRow(column(8, " ", style='padding:10px;')),
                                                   fluidRow(column(12,plotlyOutput("selected_nigeria_vac_dis_plot", height = "50vh")))
                                          )))),
                   tabPanel("About This Site", 
                            tags$div(id = "aboutPage",
                              tags$h4(strong("Background"), id = "aboutHeader"),
                              tags$h6(id = "aboutText", "Improving routine vaccination coverage is an important global health goal. Reaching and maintaining high vaccination coverage helps avoid death and illness from many preventable diseases, especially in children.",
                              tags$br(),tags$br(),"The factors that drive vaccination coverage are many and can differ between countries. The Global Vaccine Index Project is an attempt to organize data on several of these factors into a single index that allows a quick comparison between locations and across time. This project builds on prior research that identified factors that contribute to higher vaccination rates in multiple low and middle income countries.",
                              tags$br(),tags$br(),"As part of the Global Vaccine Index Project, this website offers data and resources to people interested in learning more about vaccination trends, vaccine-preventable diseases, and information on the importance of vaccines to promote health and well-being in communities around the world. "),
                              tags$br(),tags$br(),
                              tags$h4(strong("Website Last Updated"), id = "aboutHeader"),
                              h6(id = "aboutText",paste0(Sys.Date())),
                              tags$br(),tags$br(),
                              tags$h4(strong("Data Last Updated"), id = "aboutHeader"),
                              h6(id ="aboutText", paste0("2022-11-03")),
                              tags$br(),tags$br(),
                              tags$h4(strong("Sources"), id = "aboutHeader"),
                              h4(id = "aboutText", "1. Global Burden of Disease Collaborative Network.",
                              tags$a("Global Burden of Disease Study 2020, Release 1 (GBD 2020 R1) Routine Childhood Vaccination Coverage 1980-2019 [Internet]",target="_blank", href="https://ghdx.healthdata.org/record/ihme-data/gbd-2020-routine-childhood-vaccination-coverage-1980-2019"),
                              "Institute for Health Metrics and Evaluation (IHME); 2021 [cited 2021 Jul 21].",
                              tags$br(), tags$br(),
                              "2. Barau I, Zubairu M, Mwanza MN, Seaman VY. Improving polio vaccination coverage in Nigeria through the use of geographic information system technology. J Infect Dis. 2014 Nov 1;210 Suppl 1:S102-110.",
                              tags$br(), tags$br(),
                              "3. National Primary Health Care Development Agency.",
                              tags$a("Nigeria: National Routine Immunization Strategic Plan 2013-2015 | NITAG RESOURCE CENTER [Internet].",target="_blank",href="https://www.jhsph.edu/research/centers-and-institutes/ivac/resources/Nigeria-NRISP-Technical-Policy.pdf"),
                              "2013 [cited 2021 Sep 22]",
                              tags$br(), tags$br(),
                              "4. Oku A, Oyo-Ita A, Glenton C, Fretheim A, Ames H, Muloliwa A, et al. Communication strategies to promote the uptake of childhood vaccination in Nigeria: a systematic map. Glob Health Action. 2016 Feb 12;9(1).",
                              tags$br(), tags$br(),
                              "5. Ado JM, Etsano A, Shuaib F, Damisa E, Mkanda P, Gasasira A, et al. Progress toward poliomyelitis eradication in Nigeria. J Infect Dis. 2014 Nov 1;210 Suppl 1:S40-49.",
                              tags$br(), tags$br(),
                              "6. Gunnala R, Ogbuanu IU, Adegoke OJ, Scobie HM, Uba BV, Wannemuehler KA, et al. Routine Vaccination Coverage in Northern Nigeria: Results from 40 District-Level Cluster Surveys, 2014-2015. Borrow R, editor. PLOS ONE. 2016 Dec 9;11(12):e0167835.",
                              tags$br(), tags$br(),
                              "7. Oleribe O, Kumar V, Awosika-Olumo A, Taylor SD.",
                              tags$a("Individual and socioeconomic factors associated with childhood immunization coverage in Nigeria. Pan Afr Med J [Internet].",target="_blank",href="https://panafrican-med-journal.com/content/article/26/220/full/"),
                              "2017 [cited 2021 Sep 27];26.")
                            )
                   )
)
